'use client';
/* eslint-disable react-hooks/purity -- response timing is sampled only for answer events */
/* eslint-disable @next/next/no-img-element -- local transparent character PNGs */
import { useEffect, useMemo, useRef, useState } from 'react';
import { assertVocabularyIntegrity } from './vocabulary';
import { dueCount, getCurrentLearningPack, getDueQuestion, getFirstPackQuestions, learnedWordCount, loadLearningStore, recordLearningAnswer, resetLearningStore, type LearningQuestion } from './learning-engine';
import { bootstrapAnalytics, track } from './analytics';
import { SPIRITS, getSpirit, type SpiritConfig } from './game/spirit-config';
import { EPISODE_CONFIG, type EpisodeId, type MasteryLayer } from './game/episode-config';
import { bossQuestionLayer, canUsePartnerSwap, phaseCapForBoss, resolveBossQuestionLayer } from './game/progression';
import { clearGameSave, completeEpisode, confirmEp06Companion, createEmptySave, isEpisodeCompleted, isEpisodeUnlocked, loadGameSave, markEp10BossDefeated, recordEp07Swap, recordEp08Clue, recordEp09SkySilhouette, recordEp09TrackingAction, saveGameSave, setEp05Sightings, setEp06ApproachStage, setEp08MonumentFace, setEp09RareClueCount, setEp10BossPhase, type ApproachStage, type GameSave, type OpeningInteraction, type StarterId, type TrackingSlotId } from './game/save';
import { BONDING, EP1_INTRO, EP1_OUTRO, OPENING_INTERACTIONS, OPENING_PROLOGUE, POST_STORIES, STARTER_BEHAVIORS, STARTER_CHOICE_REACTIONS, STARTER_SELECTION_UI, STORIES, TEMPORARY_EPISODE_LABELS } from './narrative/temporary-content';
import type { TemporaryLine } from './narrative/types';

type Starter = StarterId;
type Episode = EpisodeId;
type Line = TemporaryLine;
const EXPLORATION = { correctNew: 3, correctReview: 2 } as const;

function spiritFor(name: Starter): SpiritConfig { return getSpirit(name); }
function titleFor(ep: Episode): string { return TEMPORARY_EPISODE_LABELS[ep].title; }
function placeFor(ep: Episode): string { return TEMPORARY_EPISODE_LABELS[ep].place; }

export default function Home() {
  const [ready, setReady] = useState(false), [save, setSave] = useState<GameSave>(createEmptySave());
  const [story, setStory] = useState<Episode | null>(null), [postStory, setPostStory] = useState<Episode | null>(null), [learning, setLearning] = useState(false), [battle, setBattle] = useState<Episode | null>(null), [arena, setArena] = useState(false), [codex, setCodex] = useState(false), [approach, setApproach] = useState(false), [monument, setMonument] = useState(false), [tracking, setTracking] = useState(false), [sky, setSky] = useState(false), [toast, setToast] = useState('');
  const [, refresh] = useState(0);
  useEffect(() => { assertVocabularyIntegrity(); const timer = window.setTimeout(() => { bootstrapAnalytics(); setSave(loadGameSave()); setReady(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (ready) saveGameSave(save); }, [ready, save]);
  const spirit = useMemo(() => save.starter ? spiritFor(save.starter) : null, [save.starter]);
  const learned = ready ? learnedWordCount() : 0, due = ready ? dueCount() : 0, pack = ready ? getCurrentLearningPack() : null;
  const update = (fn: (current: GameSave) => GameSave) => setSave(current => fn(current));
  const notify = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2600); };
  function finishOpening() { track('opening_prologue_completed'); update(s => ({ ...s, openingCheckpoint: 'station', openingIndex: 0, openingInteraction: null })); }
  function advanceOpening(index: number) { update(s => { if (s.openingInteraction) return { ...s, openingIndex: index, openingInteraction: null }; const interaction: OpeningInteraction = s.openingIndex === 3 ? 'luggage' : s.openingIndex === 8 ? 'footprints' : null; return { ...s, openingIndex: interaction ? s.openingIndex : index, openingInteraction: interaction }; }); }
  function advanceStarter(stage: number) { const beat = STARTER_BEHAVIORS[stage - 1]; if (beat) track('starter_behavior_viewed', { starter: beat.starter, step: stage }); update(s => ({ ...s, openingCheckpoint: 'station', openingIndex: stage })); }
  function choose(starter: Starter) { track('starter_selected', { starter }); const next = createEmptySave(); setSave({ ...next, starter, checkpoint: 'ep1_intro', openingCheckpoint: null }); }
  function complete(ep: Episode) { update(s => completeEpisode(s, ep)); }
  function recordBattleClear(ep: Episode) { update(s => { if (ep === 5) return { ...s, episodeState: { ...s.episodeState, ep05: { ...s.episodeState.ep05, battleCompleted: true } } }; if (ep === 7) return { ...s, episodeState: { ...s.episodeState, ep07: { ...s.episodeState.ep07, battleCompleted: true } } }; if (ep === 10) return markEp10BossDefeated(s); return s; }); }
  function learningResult(correct: boolean, seen: boolean) { if (correct) update(s => ({ ...s, exploration: s.exploration + (seen ? EXPLORATION.correctReview : EXPLORATION.correctNew) })); refresh(v => v + 1); }
  function startEpisode(ep: Episode) { track('episode_started', { episode: ep }); if (ep === 1) update(s => ({ ...s, checkpoint: 'ep1_intro', ep1TutorialIndex: 0, openingCheckpoint: null })); else setStory(ep); }
  function finishStory(ep: Episode) { track('episode_dialogue_completed', { episode: ep }); setStory(null); if (ep === 6) { setApproach(true); return; } if (ep === 8) { setMonument(true); return; } if (ep === 9) { setTracking(true); return; } if (EPISODE_CONFIG[ep].hasBattle) { setBattle(ep); return; } complete(ep); track('episode_completed', { episode: ep }); }
  function winBattle(ep: Episode) { track(ep === 10 ? 'boss_completed' : 'battle_completed', { episode: ep }); setBattle(null); recordBattleClear(ep); if (POST_STORIES[ep]) setPostStory(ep); else { complete(ep); track('episode_completed', { episode: ep }); notify(`EP${String(ep).padStart(2, '0')} · [PENDING_K3]`); } }
  function finishPost(ep: Episode) { setPostStory(null); if (ep === 9) { update(s => setEp09RareClueCount(s, 1)); setSky(true); return; } update(s => { const completed = completeEpisode(s, ep); return ep === 5 ? setEp05Sightings(completed, 3) : completed; }); track('episode_completed', { episode: ep }); notify(ep === 10 ? '第一季序章 · [PENDING_K3]' : `EP${String(ep).padStart(2, '0')} · [PENDING_K3]`); }
  function reset() { resetLearningStore(); clearGameSave(); setSave(createEmptySave()); setStory(null); setPostStory(null); setBattle(null); setApproach(false); setMonument(false); setTracking(false); setSky(false); refresh(v => v + 1); }
  if (!ready) return <main />;
  if (!spirit) return save.openingCheckpoint === 'station' ? <StarterStationGate stage={save.openingIndex} onProgress={advanceStarter} onChoose={choose} /> : <OpeningPrologueModal index={save.openingIndex} interaction={save.openingInteraction} onProgress={advanceOpening} onFinish={finishOpening} />;
  const episodeIds = Object.keys(EPISODE_CONFIG).map(Number) as Episode[];
  return <main className="p0-shell"><header className="p0-header"><div><span>《词灵》十关试玩</span><h1>雾中的回声</h1></div><div className="p0-header-actions"><div className="p0-stats"><b>{save.exploration}</b><span>探索力</span><b>{due}</b><span>到期复习</span></div><button onClick={reset}>重新开始</button></div></header>
    <section className="partner-panel"><div className={`partner-art ${spirit.tone}`}><img src={spirit.image} alt={spirit.name} /></div><div><span>我的初伴 · {spirit.roleLabel}</span><h2>{spirit.name}</h2><p>[PENDING_K3]</p><div className="evolution-hint">下一形态　<strong>？？？</strong><small>{save.companion ? '[PENDING_K3]' : '共鸣正在形成……'}</small></div>{save.companion && <div className="team-strip"><div className="unknown-mini">?</div><span><b>绒岚</b><small>MIST_PORT_SPIRIT_01 · 已共鸣</small></span></div>}</div></section>
    <nav className="home-tabs"><button onClick={() => setLearning(true)}>今日学习</button><button onClick={() => setCodex(true)}>图鉴</button><button disabled={!save.episodeState.ep08.arenaUnlocked} onClick={() => setArena(true)}>竞技场</button></nav>
    {isEpisodeCompleted(save, 10) && <ChapterMap save={save} />}
    <section className="p0-grid"><article className="p0-card learning-card"><span>今日学习</span><h2>{pack?.id} · 正式L1</h2><p>已接触 {learned}/80 词，本包 {pack?.learned}/{pack?.questions.length}。FSRS决定再次出现时间。</p><button onClick={() => setLearning(true)}>继续学习</button></article><article className="p0-card map-card"><span>探索地图</span><h2>雾港旧路</h2><div className="episode-list long-map">{episodeIds.map(ep => <EpisodeButton key={ep} episode={ep} open={isEpisodeUnlocked(save, ep)} done={isEpisodeCompleted(save, ep)} onClick={() => startEpisode(ep)} />)}</div><small>剧情只检查探索力、前置事件和必要互动，不读取固定学习包。</small></article></section>
    {save.checkpoint === 'ep1_intro' && <LinearStoryModal label="EP01 · 共鸣成立" lines={EP1_INTRO} spirit={spirit} bonding onFinish={() => update(s => ({ ...s, checkpoint: 'ep1_lesson' }))} />}{save.checkpoint === 'ep1_lesson' && <Ep1TutorialModal index={save.ep1TutorialIndex} onAnswer={learningResult} onProgress={index => update(s => ({ ...s, ep1TutorialIndex: index, checkpoint: index >= 3 ? 'ep1_outro' : 'ep1_lesson' }))} />}{save.checkpoint === 'ep1_outro' && <LinearStoryModal label="EP01 · 门外的消息" lines={EP1_OUTRO} spirit={spirit} onFinish={() => { update(s => ({ ...completeEpisode(s, 1), checkpoint: null, ep1TutorialIndex: 3 })); track('episode_completed', { episode: 1 }); }} />}
    {story && <StoryModal episode={story} spirit={spirit} onClose={() => setStory(null)} onFinish={() => finishStory(story)} />}{postStory && <PostStoryModal episode={postStory} spirit={spirit} onFinish={() => finishPost(postStory)} />}{learning && pack && <LearningModal pack={pack} onClose={() => setLearning(false)} onAnswer={learningResult} />}{battle && <BattleModal episode={battle} spirit={spirit} save={save} onClose={() => setBattle(null)} onAnswer={learningResult} onSwap={() => update(s => recordEp07Swap(s))} onBossPhase={phase => update(s => setEp10BossPhase(s, phase))} onWin={() => winBattle(battle)} />}
    {approach && <CompanionApproachModal stage={save.episodeState.ep06.approachStage} onStage={stage => update(s => setEp06ApproachStage(s, stage))} onConfirm={() => { setApproach(false); update(s => completeEpisode(confirmEp06Companion(s), 6)); track('episode_completed', { episode: 6 }); }} />}{monument && <MonumentModal state={save} onFace={face => update(s => setEp08MonumentFace(s, face))} onClue={clue => update(s => recordEp08Clue(s, clue))} onComplete={() => { setMonument(false); update(s => completeEpisode(recordEp08Clue(recordEp08Clue(s, 'residue'), 'position'), 8)); track('episode_completed', { episode: 8 }); }} onArena={() => setArena(true)} />}{tracking && <TrackingModal state={save} onAction={slot => update(s => recordEp09TrackingAction(s, slot))} onAnswer={learningResult} onComplete={() => { setTracking(false); setBattle(9); }} />}{sky && <SkySilhouetteModal onComplete={() => { setSky(false); update(s => completeEpisode(recordEp09SkySilhouette(setEp09RareClueCount(s, 1)), 9)); track('episode_completed', { episode: 9 }); }} />}
    {arena && <ArenaModal onClose={() => setArena(false)} onComplete={() => { update(s => ({ ...s, arenaDone: true, exploration: s.exploration + 4, episodeState: { ...s.episodeState, ep08: { ...s.episodeState.ep08, arenaSnapshotCompleted: true } } })); setArena(false); notify('竞技快照已记录'); }} />}{codex && <CodexModal save={save} spirit={spirit} onClose={() => setCodex(false)} />}{toast && <div className="toast">{toast}</div>}</main>;
}

function OpeningPrologueModal({ index, interaction, onProgress, onFinish }: { index: number; interaction: OpeningInteraction; onProgress: (index: number) => void; onFinish: () => void }) { const safe = Math.min(index, OPENING_PROLOGUE.length - 1), line = OPENING_PROLOGUE[safe]; const next = () => { if (interaction) onProgress(safe + 1); else if (safe === 3 || safe === 8) onProgress(safe); else if (safe < OPENING_PROLOGUE.length - 1) onProgress(safe + 1); else onFinish(); }; useEffect(() => { track('opening_prologue_started'); }, []); if (interaction) { const copy = OPENING_INTERACTIONS[interaction]; return <main className="starter-screen opening-screen"><section className="story-modal opening-modal opening-interaction"><span>序章 · {interaction === 'luggage' ? '码头边' : '旧渡口边'}</span><div className="story-stage"><div className="scene-symbol opening-scene opening-interaction-scene">{interaction === 'luggage' ? '木板' : '脚印'}</div><div><b>{copy.label}</b><p>{copy.text}</p></div></div><button className="story-next" onClick={next}>{copy.action}</button></section></main>; } return <main className="starter-screen opening-screen"><section className="story-modal opening-modal"><span>序章 · 雾港</span><div className="story-stage"><div className="scene-symbol opening-scene">{safe < 5 ? '码头' : safe < 10 ? '旧渡口' : '语灵站'}</div><div><b>{line[0]}</b><p>{line[1]}</p></div></div><button className="story-next" onClick={next}>{safe < OPENING_PROLOGUE.length - 1 ? '继续' : '进入语灵站'}</button></section></main>; }

function StarterStationGate({ stage, onProgress, onChoose }: { stage: number; onProgress: (stage: number) => void; onChoose: (starter: Starter) => void }) { const behavior = STARTER_BEHAVIORS[Math.min(stage, STARTER_BEHAVIORS.length - 1)], spirit = spiritFor(behavior.starter); if (stage < STARTER_BEHAVIORS.length) return <main className="starter-screen station-screen"><section className="story-modal station-modal"><span>序章 · 语灵站　观察 {stage + 1}/3</span><div className={`story-stage station-behavior ${spirit.tone}`}><div className="starter-art"><img className="spirit-art" src={spirit.image} alt={spirit.name} /></div><div><b>{spirit.name}</b><p>{behavior.text}</p><small>{behavior.detail}</small></div></div><button className="story-next" onClick={() => onProgress(stage + 1)}>{stage < 2 ? '继续观察' : '看看它们愿不愿意跟你走'}</button></section></main>; return <StarterGate onChoose={onChoose} />; }
function StarterGate({ onChoose }: { onChoose: (starter: Starter) => void }) { return <main className="starter-screen"><section className="starter-dialogue"><span>序章 · 语灵站</span><h1>{STARTER_SELECTION_UI.title}</h1><p>{STARTER_SELECTION_UI.prompt}</p></section><section className="starter-grid">{SPIRITS.map(spirit => <article className={`starter-card ${spirit.tone}`} key={spirit.name}><div className="starter-art"><img className="spirit-art" src={spirit.image} alt={spirit.name} /></div><h2>{spirit.name}</h2><p>{STARTER_CHOICE_REACTIONS[spirit.name]}</p><button onClick={() => onChoose(spirit.name)}>我想和{spirit.name}一起走</button></article>)}</section><small className="starter-note">{STARTER_SELECTION_UI.note}</small></main>; }
function EpisodeButton({ episode, open, done, onClick }: { episode: Episode; open: boolean; done: boolean; onClick: () => void }) { return <button className={done ? 'done' : ''} disabled={!open || done} onClick={onClick}><i>{done ? '✓' : episode}</i><span>EP{String(episode).padStart(2, '0')} · {placeFor(episode)}<b>{titleFor(episode)}</b></span><em>{done ? '已完成' : open ? '进入' : '未解锁'}</em></button>; }
function StoryModal({ episode, spirit, onClose, onFinish }: { episode: Episode; spirit: SpiritConfig; onClose: () => void; onFinish: () => void }) { const lines = STORIES[episode] ?? ([['[PENDING_K3]', '[PENDING_K3]']] as const); const [index, setIndex] = useState(0), line = lines[Math.min(index, lines.length - 1)], visual = episode === 4 ? '尾' : episode === 8 ? '碑' : episode === 9 ? '稀' : episode === 10 ? '守' : null; return <div className="modal-backdrop"><section className="story-modal"><button className="close" onClick={onClose}>×</button><span>EP{String(episode).padStart(2, '0')} · {placeFor(episode)}</span><div className="story-stage">{visual ? <div className={`scene-symbol scene-${episode}`}>{visual}</div> : <img src={spirit.image} alt={spirit.name} />}<div><b>{line[0]}</b><p>{line[1]}</p></div></div><button className="story-next" onClick={() => index < lines.length - 1 ? setIndex(index + 1) : onFinish()}>{index < lines.length - 1 ? '继续' : EPISODE_CONFIG[episode].hasBattle ? '进入战斗' : '继续'}</button></section></div>; }
function LinearStoryModal({ label, lines, spirit, bonding = false, onFinish }: { label: string; lines: readonly Line[]; spirit: SpiritConfig; bonding?: boolean; onFinish: () => void }) { const [index, setIndex] = useState(0), line = lines[Math.min(index, lines.length - 1)], bond = bonding && index === 0; return <div className="modal-backdrop intro-backdrop"><section className="story-modal"><span>{label}</span><div className="story-stage"><img src={spirit.image} alt={spirit.name} /><div><b>{bond ? spirit.name : line[0]}</b><p>{bond ? BONDING[spirit.name] : line[1]}</p></div></div><button className="story-next" onClick={() => index < lines.length - 1 ? setIndex(index + 1) : onFinish()}>{index < lines.length - 1 ? '继续' : '前往港外旧路'}</button></section></div>; }
function Ep1TutorialModal({ index, onAnswer, onProgress }: { index: number; onAnswer: (correct: boolean, seen: boolean) => void; onProgress: (index: number) => void }) {
  const questions = getFirstPackQuestions().slice(0, 3), question = questions[Math.min(index, 2)];
  const [feedback, setFeedback] = useState(''); const started = useRef(0);
  useEffect(() => { track('lesson_started', { packId: 'EP01_TUTORIAL' }); started.current = Date.now(); }, []);
  function answer(choice: string) { const store = loadLearningStore(); const seen = (store.progress[question.wordId]?.attempts ?? 0) > 0; const correct = choice === question.answer; recordLearningAnswer(question, correct, Date.now() - started.current); track('question_answered', { wordId: question.wordId, layer: 'L1', correct, source: 'ep01_tutorial' }); onAnswer(correct, seen); setFeedback(correct ? '它回应了你的声音。' : `正确义项：${question.answer}`); window.setTimeout(() => { setFeedback(''); onProgress(index + 1); started.current = Date.now(); }, 650); }
  return <div className="modal-backdrop intro-backdrop"><section className="learn-sheet ep1-tutorial"><span>EP01 · 第一次真正认识　{index + 1}/3</span><h2>{question.word}</h2><i>{question.phonetic}</i><p>{question.prompt}</p><div>{question.choices.map(choice => <button key={choice} disabled={!!feedback} onClick={() => answer(choice)}>{choice}</button>)}</div>{feedback && <strong>{feedback}</strong>}<small>完成3个L1后剧情会在语灵站内继续，不跳回首页。</small></section></div>;
}

function LearningModal({ pack, onClose, onAnswer }: { pack: ReturnType<typeof getCurrentLearningPack>; onClose: () => void; onAnswer: (correct: boolean, seen: boolean) => void }) {
  const [index, setIndex] = useState(Math.min(pack.learned, pack.questions.length - 1)); const [feedback, setFeedback] = useState(''); const started = useRef(0); const question = pack.questions[index];
  useEffect(() => { track('lesson_started', { packId: pack.id }); started.current = Date.now(); }, [pack.id]);
  function answer(choice: string) { const seen = index < pack.learned; const correct = choice === question.answer; recordLearningAnswer(question, correct, Date.now() - started.current); track('question_answered', { wordId: question.wordId, layer: question.layer, correct, source: 'lesson' }); onAnswer(correct, seen); setFeedback(correct ? '记住了。探索力正在汇聚。' : `正确义项：${question.answer}`); window.setTimeout(() => { setFeedback(''); if (index < pack.questions.length - 1) { setIndex(index + 1); started.current = Date.now(); } else { onClose(); } }, 650); }
  return <div className="modal-backdrop"><section className="learn-sheet"><button className="close" onClick={onClose}>×</button><span>{pack.id} · L1　{index + 1}/{pack.questions.length}</span><h2>{question.word}</h2><i>{question.phonetic}</i><p>{question.prompt}</p><div>{question.choices.map(choice => <button key={choice} disabled={!!feedback} onClick={() => answer(choice)}>{choice}</button>)}</div>{feedback && <strong>{feedback}</strong>}</section></div>;
}

type BattleProps = { episode: Episode; spirit: SpiritConfig; save: GameSave; onClose: () => void; onAnswer: (correct: boolean, seen: boolean) => void; onSwap: () => void; onBossPhase: (phase: 1 | 2 | 3) => void; onWin: () => void };
function BattleModal({ episode, spirit, save, onClose, onAnswer, onSwap, onBossPhase, onWin }: BattleProps) {
  const boss = episode === 10, requiresSwap = episode === 7, initialEnemy = boss ? 72 : episode === 9 ? 120 : requiresSwap ? 96 : 100;
  const [enemy, setEnemy] = useState(initialEnemy), [ally, setAlly] = useState(100), [phase, setPhase] = useState<1 | 2 | 3>(1), [question, setQuestion] = useState<LearningQuestion | null>(null), [skill, setSkill] = useState(spirit.skills[0]), [message, setMessage] = useState('[PENDING_K3]'), [wrongId, setWrongId] = useState<string>(), [wrongStreak, setWrongStreak] = useState(0), [swapped, setSwapped] = useState(save.episodeState.ep07.swapUsed), [defeated, setDefeated] = useState(false);
  const outcome = useRef<'active' | 'won' | 'defeated'>('active'); const started = useRef(0); const timer = useRef<ReturnType<typeof setTimeout> | null>(null); useEffect(() => () => { if (timer.current) window.clearTimeout(timer.current); }, []);
  const playerCeiling: MasteryLayer = 'L1', approved: MasteryLayer = 'L1'; const displayedLayer = boss ? resolveBossQuestionLayer(phaseCapForBoss(phase), playerCeiling, approved) : 'L1'; const teamSize = save.episodeState.ep06.teamSpiritIds.length || (save.companion ? 2 : 1);
  function chooseSkill(nextSkill: typeof skill) { if (outcome.current !== 'active') return; if (requiresSwap && !swapped) { setMessage('[PENDING_K3] · 先完成换位'); return; } setSkill(nextSkill); setQuestion(getDueQuestion(wrongId) ?? getFirstPackQuestions()[0] ?? null); started.current = Date.now(); }
  function swap() { if (!requiresSwap || swapped || !canUsePartnerSwap(save)) return; setSwapped(true); onSwap(); setMessage('[PENDING_K3]'); }
  function retry() { setEnemy(initialEnemy); setAlly(100); setPhase(1); setQuestion(null); setSkill(spirit.skills[0]); setWrongId(undefined); setWrongStreak(0); setDefeated(false); setMessage('[PENDING_K3]'); outcome.current = 'active'; }
  function answer(choice: string) { if (!question || outcome.current !== 'active') return; const correct = choice === question.answer, store = loadLearningStore(), seen = (store.progress[question.wordId]?.attempts ?? 0) > 0; recordLearningAnswer(question, correct, Date.now() - started.current); track('question_answered', { wordId: question.wordId, layer: question.layer, correct, source: `battle_ep${episode}` }); onAnswer(correct, seen); setQuestion(null); if (!correct) { const streak = wrongStreak + 1; setWrongId(question.wordId); setWrongStreak(streak); const hp = Math.max(0, ally - (boss ? 22 : 16)); setAlly(hp); setMessage(streak >= 2 ? '[PENDING_K3] · 题层降至L1' : `错误：${question.word} · FSRS已重新调度`); if (hp === 0) { outcome.current = 'defeated'; setDefeated(true); } return; } setWrongId(undefined); setWrongStreak(0); const damage = skill.name === '焰尾' ? 42 : swapped ? 30 : 20, next = Math.max(0, enemy - damage); if (next > 0) { setEnemy(next); setMessage(`L1 · ${skill.name} · [PENDING_K3]`); return; } if (boss && phase < 3) { const nextPhase = (phase + 1) as 1 | 2 | 3; setPhase(nextPhase); setEnemy(initialEnemy); onBossPhase(nextPhase); setMessage(`[PENDING_K3] · Phase ${nextPhase} · ${bossQuestionLayer(save, 'L1', 'L1')}`); return; } outcome.current = 'won'; setEnemy(0); timer.current = window.setTimeout(onWin, 350); }
  const body = defeated ? <div className="battle-skills battle-defeat"><button onClick={retry}><b>重新挑战</b><small>保留已记录的学习结果</small></button><button onClick={onClose}><b>暂时退出</b><small>当前剧情节点未完成</small></button></div> : question ? <div className="battle-question"><h3>{question.word}</h3><small>{question.phonetic} · {displayedLayer}</small>{question.choices.map(choice => <button key={choice} onClick={() => answer(choice)}>{choice}</button>)}</div> : <div className="battle-skills">{spirit.skills.map(item => <button key={item.name} onClick={() => chooseSkill(item)}><b>{item.name}</b><small>{item.effect}</small></button>)}{requiresSwap && teamSize >= 2 && <button className={swapped ? 'used' : ''} onClick={swap} disabled={swapped}><b>换位</b><small>{swapped ? '已完成配合' : '冷却0 · 不触发英语题'}</small></button>}</div>;
  return <div className="modal-backdrop"><section className="p0-battle"><button className="close" onClick={onClose}>×</button><span>EP{String(episode).padStart(2, '0')} · {boss ? `Boss · Phase ${phase}` : episode === 9 ? '稀有试探战' : episode === 7 ? '双伙伴战斗' : '探索战斗'}</span><h2>{boss ? 'EP10 · [PENDING_K3]' : titleFor(episode)}</h2><div className="battle-health"><b>{spirit.name} {ally}</b><b>目标 {enemy}</b></div><div className="battle-figures"><div className="battle-team-visual"><img src={spirit.image} alt={spirit.name} />{teamSize >= 2 && <div className="unknown-fighter">绒</div>}</div><strong>VS</strong><div className={`shadow-foe ${boss ? 'gatekeeper' : ''}`}>{boss ? '守' : episode === 9 ? '稀' : '蚀'}</div></div><p>{message}</p>{body}<small className="battle-rule">题层：{displayedLayer} · FSRS只负责调度；未审校高层内容不会临时生成。</small></section></div>;
}
function CompanionApproachModal({ stage, onStage, onConfirm }: { stage: ApproachStage; onStage: (stage: ApproachStage) => void; onConfirm: () => void }) { const complete = stage >= 3, next = Math.min(3, stage + 1) as ApproachStage; return <div className="modal-backdrop"><section className="skeleton-modal"><span>EP06 · interaction {stage}/3</span><h2>绒岚 · [PENDING_K3]</h2><p>[PENDING_K3]</p><div className="skeleton-steps">{[1, 2, 3].map(step => <i className={stage >= step ? 'active' : ''} key={step}>interaction_{step}</i>)}</div>{complete ? <button className="story-next" onClick={onConfirm}>确认获得 MIST_PORT_SPIRIT_01</button> : <button className="story-next" onClick={() => onStage(next)}>完成 interaction {next}</button>}</section></div>; }
function MonumentModal({ state, onFace, onClue, onComplete, onArena }: { state: GameSave; onFace: (face: 'front' | 'back') => void; onClue: (clue: 'residue' | 'position') => void; onComplete: () => void; onArena: () => void }) { const monument = state.episodeState.ep08, ready = monument.residueRecorded && monument.positionRecorded; return <div className="modal-backdrop"><section className="skeleton-modal"><span>EP08 · unnamed monument</span><h2>无名碑 · [PENDING_K3]</h2><div className="skeleton-actions"><button className={monument.monumentFace === 'front' ? 'active' : ''} onClick={() => onFace('front')}>查看正面</button><button className={monument.monumentFace === 'back' ? 'active' : ''} onClick={() => onFace('back')}>查看背面</button><button disabled={monument.residueRecorded} onClick={() => onClue('residue')}>记录残字</button><button disabled={monument.positionRecorded} onClick={() => onClue('position')}>记录位置</button></div><p>[PENDING_K3]</p><div className="skeleton-status">残字 {monument.residueRecorded ? '✓' : '—'}　位置 {monument.positionRecorded ? '✓' : '—'}</div>{monument.arenaUnlocked && <button className="skeleton-subaction" onClick={onArena}>竞技快照（可选）</button>}<button className="story-next" disabled={!ready} onClick={onComplete}>完成记录并继续</button></section></div>; }
function TrackingModal({ state, onAction, onAnswer, onComplete }: { state: GameSave; onAction: (slot: TrackingSlotId) => void; onAnswer: (correct: boolean, seen: boolean) => void; onComplete: () => void }) { const slots: TrackingSlotId[] = ['tracking_01', 'tracking_02', 'tracking_03'], complete = slots.every(slot => state.episodeState.ep09.tracking[slot].completed); const [activeSlot, setActiveSlot] = useState<TrackingSlotId | null>(null), [question, setQuestion] = useState<LearningQuestion | null>(null), started = useRef(0); function start(slot: TrackingSlotId) { setActiveSlot(slot); setQuestion(getDueQuestion()); started.current = Date.now(); } function answer(choice: string) { if (!question || !activeSlot) return; const store = loadLearningStore(), correct = choice === question.answer, seen = (store.progress[question.wordId]?.attempts ?? 0) > 0; recordLearningAnswer(question, correct, Date.now() - started.current); track('question_answered', { wordId: question.wordId, layer: 'L1', correct, source: `ep09_${activeSlot}` }); onAnswer(correct, seen); onAction(activeSlot); setActiveSlot(null); setQuestion(null); } if (question && activeSlot) return <div className="modal-backdrop"><section className="skeleton-modal"><span>EP09 · {activeSlot} · L1</span><h2>{question.word}</h2><p>{question.prompt}</p><div className="tracking-question">{question.choices.map(choice => <button key={choice} onClick={() => answer(choice)}>{choice}</button>)}</div></section></div>; return <div className="modal-backdrop"><section className="skeleton-modal"><span>EP09 · tracking slots</span><h2>雾坡 · [PENDING_K3]</h2><p>每处只进行一次必要英语行动。</p><div className="tracking-grid">{slots.map(slot => { const item = state.episodeState.ep09.tracking[slot]; return <button key={slot} disabled={item.completed} onClick={() => start(slot)}><b>{slot}</b><small>{item.completed ? 'L1 action ✓' : '执行1次L1 action'}</small></button>; })}</div><button className="story-next" disabled={!complete} onClick={onComplete}>进入稀有试探战</button></section></div>; }
function SkySilhouetteModal({ onComplete }: { onComplete: () => void }) { return <div className="modal-backdrop"><section className="skeleton-modal"><span>EP09 · sky silhouette</span><h2>SKY_LEGEND_01</h2><p>[PENDING_K3]</p><div className="sky-placeholder">翼</div><button className="story-next" onClick={onComplete}>记录天空剪影</button></section></div>; }
function PostStoryModal({ episode, spirit, onFinish }: { episode: Episode; spirit: SpiritConfig; onFinish: () => void }) { const lines = POST_STORIES[episode] ?? ([['[PENDING_K3]', '[PENDING_K3]']] as const), [index, setIndex] = useState(0), line = lines[Math.min(index, lines.length - 1)]; return <div className="modal-backdrop"><section className="story-modal"><span>EP{String(episode).padStart(2, '0')} · 战后</span><div className="story-stage">{episode === 10 ? <div className="scene-symbol scene-10">守</div> : <img src={spirit.image} alt={spirit.name} />}<div><b>{line[0]}</b><p>{line[1]}</p></div></div><button className="story-next" onClick={() => index < lines.length - 1 ? setIndex(index + 1) : onFinish()}>{index < lines.length - 1 ? '继续' : '完成剧情'}</button></section></div>; }
function ArenaModal({ onClose, onComplete }: { onClose: () => void; onComplete: () => void }) { const [round, setRound] = useState(0); return <div className="modal-backdrop"><section className="story-modal arena-modal"><button className="close" onClick={onClose}>×</button><span>旧擂台 · 测试快照</span><h2>[PENDING_K3]</h2><p>当前仅为本地测试快照，不是真实异步竞技。</p><div className="arena-snapshot"><b>攻击</b><span>当前作答结果</span><b>防守/反击</b><span>历史掌握快照</span></div><button className="story-next" onClick={() => round < 2 ? setRound(round + 1) : onComplete()}>{round < 2 ? `完成模拟回合 ${round + 1}/3` : '结束首场竞技'}</button></section></div>; }
function ChapterMap({ save }: { save: GameSave }) { const hooks = save.episodeState.ep10.hookFlags; return <section className="chapter-map"><span>章末地图 · 数据状态</span><h2>[PENDING_K3]</h2><div><i>map.harbor</i><i>map.unnamed_outline</i><i>map.next_outline</i></div><ul><li>starter_evolution: {hooks.starterEvolution ? 'ready' : 'pending'}</li><li>MIST_PORT_RARE_01 · {save.episodeState.ep09.rareClueCount}/3</li><li>SKY_LEGEND_01 · {hooks.skyLegend ? 'recorded' : 'pending'}</li></ul></section>; }
function CodexModal({ save, spirit, onClose }: { save: GameSave; spirit: SpiritConfig; onClose: () => void }) { return <div className="modal-backdrop"><section className="story-modal codex-modal"><button className="close" onClick={onClose}>×</button><span>雾港图鉴</span><h2>见过的语灵</h2><div className="codex-list"><article><img src={spirit.image} alt={spirit.name} /><b>{spirit.name}</b><small>初伴 · 已共鸣 · 下一形态？？？</small></article><article><div className="unknown-mini">?</div><b>{save.sightings > 0 ? '绒岚' : '？？？'}</b><small>{save.sightings > 0 ? `MIST_PORT_SPIRIT_01 · ${save.companion ? '已共鸣' : `未共鸣 · 目击 ${save.sightings}/3`}` : '尚未见过'}</small></article><article><div className="rare-mini">稀</div><b>{save.rareSeen ? '未记录稀客' : '？？？'}</b><small>{save.rareSeen ? `未共鸣 · 线索${save.episodeState.ep09.rareClueCount}/3` : '尚未见过'}</small></article><article><div className="sky-mini">翼</div><b>天空剪影</b><small>{save.episodeState.ep09.skySilhouetteSeen ? 'SKY_LEGEND_01 · 已记录' : '尚未记录'}</small></article></div></section></div>; }
