'use client';
/* eslint-disable react-hooks/purity -- response timing is sampled only for answer events */
/* eslint-disable @next/next/no-img-element -- local transparent character PNGs */
import { useEffect, useMemo, useRef, useState } from 'react';
import { assertVocabularyIntegrity } from './vocabulary';
import { dueCount, getCurrentLearningPack, getDueQuestion, getFirstPackQuestions, learnedWordCount, loadLearningStore, recordLearningAnswer, resetLearningStore, type LearningQuestion } from './learning-engine';
import { bootstrapAnalytics, track } from './analytics';
import { SPIRITS, getSpirit, type SpiritConfig } from './game/spirit-config';
import { EPISODE_CONFIG, type EpisodeId, type MasteryLayer } from './game/episode-config';
import { bossQuestionLayer, phaseCapForBoss, resolveBossQuestionLayer } from './game/progression';
import { getSpiritGrowth, grantBattleGrowth, grantLearningGrowth, grantResonanceMilestone } from './game/growth';
import { MIST_PORT_TACTICS, applyTeamTactic, createTeamBattleState, getActiveSpirit, getReserveSpirits, getSwapAvailability, getSwapCue, resolveEnemyTurn, setNextEnemyAttack, swapActiveSpirit, type TeamBattleState } from './game/team-battle';
import { DevPanel } from './game/dev-panel';
import type { DevPresetResult } from './game/dev-presets';
import { appendBattleLog, type BattleLogEventInput } from './game/battle-log';
import { clearGameSave, completeEp08ArenaSnapshot, completeEpisode, confirmEp06Companion, createEmptySave, isEpisodeCompleted, isEpisodeUnlocked, loadGameSave, markEp10BossDefeated, recordEp07Swap, recordEp08Clue, recordEp09SkySilhouette, recordEp09TrackingAction, saveGameSave, setEp05Sightings, setEp06ApproachStage, setEp08MonumentFace, setEp09RareClueCount, setEp10BossPhase, type ApproachStage, type GameSave, type OpeningInteraction, type StarterId, type TrackingSlotId } from './game/save';
import { BONDING, EP1_INTRO, EP1_OUTRO, OPENING_INTERACTIONS, OPENING_PROLOGUE, POST_STORIES, STARTER_BEHAVIORS, STARTER_CHOICE_REACTIONS, STARTER_SELECTION_UI, STORIES, TEMPORARY_EPISODE_LABELS } from './narrative/temporary-content';
import type { TemporaryLine } from './narrative/types';

type Starter = StarterId;
type Episode = EpisodeId;
type Line = TemporaryLine;
const EXPLORATION = { correctNew: 3, correctReview: 2 } as const;

function spiritFor(name: Starter): SpiritConfig { return getSpirit(name); }
function titleFor(ep: Episode): string { return TEMPORARY_EPISODE_LABELS[ep].title; }
function placeFor(ep: Episode): string { return TEMPORARY_EPISODE_LABELS[ep].place; }
function resonanceStage(value: number): string { if (value >= 12) return '征兆'; if (value >= 7) return '并肩'; if (value >= 3) return '熟悉'; return '初识'; }
function resonanceHint(value: number): string { return value >= 12 ? '出现新的变化征兆' : value >= 7 ? '并肩感正在增强' : value >= 3 ? '共鸣纹理已经改变' : '共鸣正在形成'; }

export default function Home() {
  const [ready, setReady] = useState(false), [save, setSave] = useState<GameSave>(createEmptySave());
  const [story, setStory] = useState<Episode | null>(null), [postStory, setPostStory] = useState<Episode | null>(null), [learning, setLearning] = useState(false), [battle, setBattle] = useState<Episode | null>(null), [arena, setArena] = useState(false), [codex, setCodex] = useState(false), [approach, setApproach] = useState(false), [monument, setMonument] = useState(false), [tracking, setTracking] = useState(false), [sky, setSky] = useState(false), [toast, setToast] = useState('');
  const [, refresh] = useState(0);
  useEffect(() => { assertVocabularyIntegrity(); const timer = window.setTimeout(() => { bootstrapAnalytics(); setSave(loadGameSave()); setReady(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (ready) saveGameSave(save); }, [ready, save]);
  const spirit = useMemo(() => save.starter ? spiritFor(save.starter) : null, [save.starter]);
  const starterGrowth = save.starter ? getSpiritGrowth(save, save.starter) : null;
  const companionGrowth = getSpiritGrowth(save, 'MIST_PORT_SPIRIT_01');
  const learned = ready ? learnedWordCount() : 0, due = ready ? dueCount() : 0, pack = ready ? getCurrentLearningPack() : null;
  const update = (fn: (current: GameSave) => GameSave) => setSave(current => fn(current));
  const notify = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2600); };
  function finishOpening() { track('opening_prologue_completed'); update(s => ({ ...s, openingCheckpoint: 'station', openingIndex: 0, openingInteraction: null })); }
  function advanceOpening(index: number) { update(s => { if (s.openingInteraction) return { ...s, openingIndex: index, openingInteraction: null }; const interaction: OpeningInteraction = s.openingIndex === 3 ? 'luggage' : s.openingIndex === 8 ? 'footprints' : null; return { ...s, openingIndex: interaction ? s.openingIndex : index, openingInteraction: interaction }; }); }
  function advanceStarter(stage: number) { const beat = STARTER_BEHAVIORS[stage - 1]; if (beat) track('starter_behavior_viewed', { starter: beat.starter, step: stage }); update(s => ({ ...s, openingCheckpoint: 'station', openingIndex: stage })); }
  function choose(starter: Starter) { track('starter_selected', { starter }); const next = createEmptySave(); setSave({ ...next, starter, checkpoint: 'ep1_intro', openingCheckpoint: null }); }
  function complete(ep: Episode) { update(s => completeEpisode(s, ep)); }
  function recordBattleClear(ep: Episode) { update(s => { let next = s; if (ep === 5) next = { ...next, episodeState: { ...next.episodeState, ep05: { ...next.episodeState.ep05, battleCompleted: true } } }; if (ep === 7) next = { ...next, episodeState: { ...next.episodeState, ep07: { ...next.episodeState.ep07, battleCompleted: true } } }; if (ep === 10) next = markEp10BossDefeated(next); if (next.starter) next = grantBattleGrowth(next, next.starter, `ep${String(ep).padStart(2, '0')}`).save; if (ep === 7 && next.starter) next = grantResonanceMilestone(next, 'ep07.teamwork', [next.starter, 'MIST_PORT_SPIRIT_01'], 3); if (ep === 10 && next.starter) next = grantResonanceMilestone(next, 'ep10.chapter_clear', [next.starter, 'MIST_PORT_SPIRIT_01'], 5); return next; }); }
  function learningResult(correct: boolean, seen: boolean, question?: LearningQuestion, activeSpiritId?: string) { if (correct) { const spiritId = activeSpiritId ?? save.starter; const attempts = question ? (loadLearningStore().progress[question.wordId]?.attempts ?? 0) : 0; const evidenceId = question ? `learning:${question.wordId}:${attempts}` : null; if (spiritId && evidenceId) { const preview = grantLearningGrowth(save, spiritId, evidenceId, seen); if (!preview.duplicate) notify(preview.toLevel > preview.fromLevel ? `${spiritId}升到 Lv.${preview.toLevel}` : `${spiritId} +${preview.xp}经验 · 共鸣+${preview.resonance}`); } update(s => { const explored = { ...s, exploration: s.exploration + (seen ? EXPLORATION.correctReview : EXPLORATION.correctNew) }; return spiritId && evidenceId ? grantLearningGrowth(explored, spiritId, evidenceId, seen).save : explored; }); } refresh(v => v + 1); }
  function startEpisode(ep: Episode) { track('episode_started', { episode: ep }); if (ep === 1) update(s => ({ ...s, checkpoint: 'ep1_intro', ep1TutorialIndex: 0, openingCheckpoint: null })); else setStory(ep); }
  function finishStory(ep: Episode) { track('episode_dialogue_completed', { episode: ep }); setStory(null); if (ep === 6) { setApproach(true); return; } if (ep === 8) { setMonument(true); return; } if (ep === 9) { setTracking(true); return; } if (EPISODE_CONFIG[ep].hasBattle) { setBattle(ep); return; } complete(ep); track('episode_completed', { episode: ep }); }
  function winBattle(ep: Episode) { track(ep === 10 ? 'boss_completed' : 'battle_completed', { episode: ep }); setBattle(null); recordBattleClear(ep); if (POST_STORIES[ep]) setPostStory(ep); else { complete(ep); track('episode_completed', { episode: ep }); notify(`EP${String(ep).padStart(2, '0')} · [PENDING_K3]`); } }
  function finishPost(ep: Episode) { setPostStory(null); if (ep === 9) { update(s => setEp09RareClueCount(s, 1)); setSky(true); return; } update(s => { const completed = completeEpisode(s, ep); return ep === 5 ? setEp05Sightings(completed, 3) : completed; }); track('episode_completed', { episode: ep }); notify(ep === 10 ? '第一季序章 · [PENDING_K3]' : `EP${String(ep).padStart(2, '0')} · [PENDING_K3]`); }
  function reset() { resetLearningStore(); clearGameSave(); setSave(createEmptySave()); setStory(null); setPostStory(null); setBattle(null); setApproach(false); setMonument(false); setTracking(false); setSky(false); refresh(v => v + 1); }
  function applyDevPreset(result: DevPresetResult) { setSave(result.save); setStory(null); setPostStory(null); setBattle(null); setApproach(false); setMonument(false); setTracking(false); setSky(false); if (result.entry.kind === 'battle') setBattle(result.target); else if (result.entry.kind === 'node' && result.target === 6) setApproach(true); else if (result.entry.kind === 'node' && result.target === 8) setMonument(true); else if (result.entry.kind === 'node' && result.target === 9) setTracking(true); else setStory(result.target); }
  if (!ready) return <main />;
  if (!spirit) return <>{save.openingCheckpoint === 'station' ? <StarterStationGate stage={save.openingIndex} onProgress={advanceStarter} onChoose={choose} /> : <OpeningPrologueModal index={save.openingIndex} interaction={save.openingInteraction} onProgress={advanceOpening} onFinish={finishOpening} />}{process.env.NODE_ENV === 'development' && <DevPanel save={save} onApply={applyDevPreset} onReplaceSave={setSave} onClear={() => { clearGameSave(); setSave(createEmptySave()); }} />}</>;
  const episodeIds = Object.keys(EPISODE_CONFIG).map(Number) as Episode[];
  return <main className="p0-shell"><header className="p0-header"><div><span>《词灵》十关试玩</span><h1>雾中的回声</h1></div><div className="p0-header-actions"><div className="p0-stats"><b>{save.exploration}</b><span>探索力</span><b>{due}</b><span>到期复习</span></div><button onClick={reset}>重新开始</button></div></header>
    <section className="partner-panel"><div className={`partner-art ${spirit.tone}`}><img src={spirit.image} alt={spirit.name} /></div><div><span>我的初伴 · {spirit.roleLabel}</span><h2>{spirit.name}</h2><p>Lv.{starterGrowth?.level ?? 1} · 经验 {starterGrowth?.xp ?? 0} · 共鸣阶段 {resonanceStage(starterGrowth?.resonance ?? 0)}</p><div className="evolution-hint">下一形态　<strong>？？？</strong><small>{resonanceHint(starterGrowth?.resonance ?? 0)}</small></div>{save.companion && <div className="team-strip"><div className="unknown-mini">?</div><span><b>绒岚 · Lv.{companionGrowth.level}</b><small>共鸣阶段 {resonanceStage(companionGrowth.resonance)} · 下一形态？？？</small></span></div>}</div></section>
    <nav className="home-tabs"><button onClick={() => setLearning(true)}>今日学习</button><button onClick={() => setCodex(true)}>图鉴</button><button disabled={!save.episodeState.ep08.arenaUnlocked} onClick={() => setArena(true)}>竞技场</button></nav>
    {isEpisodeCompleted(save, 10) && <ChapterMap save={save} />}
    <section className="p0-grid"><article className="p0-card learning-card"><span>今日学习</span><h2>{pack?.id} · 正式L1</h2><p>已接触 {learned}/80 词，本包 {pack?.learned}/{pack?.questions.length}。FSRS决定再次出现时间。</p><button onClick={() => setLearning(true)}>继续学习</button></article><article className="p0-card map-card"><span>探索地图</span><h2>雾港旧路</h2><div className="episode-list long-map">{episodeIds.map(ep => <EpisodeButton key={ep} episode={ep} open={isEpisodeUnlocked(save, ep)} done={isEpisodeCompleted(save, ep)} onClick={() => startEpisode(ep)} />)}</div><small>剧情只检查探索力、前置事件和必要互动，不读取固定学习包。</small></article></section>
    {save.checkpoint === 'ep1_intro' && <LinearStoryModal label="EP01 · 共鸣成立" lines={EP1_INTRO} spirit={spirit} bonding onFinish={() => update(s => ({ ...s, checkpoint: 'ep1_lesson' }))} />}{save.checkpoint === 'ep1_lesson' && <Ep1TutorialModal index={save.ep1TutorialIndex} onAnswer={learningResult} onProgress={index => update(s => ({ ...s, ep1TutorialIndex: index, checkpoint: index >= 3 ? 'ep1_outro' : 'ep1_lesson' }))} />}{save.checkpoint === 'ep1_outro' && <LinearStoryModal label="EP01 · 门外的消息" lines={EP1_OUTRO} spirit={spirit} onFinish={() => { update(s => ({ ...completeEpisode(s, 1), checkpoint: null, ep1TutorialIndex: 3 })); track('episode_completed', { episode: 1 }); }} />}
    {story && <StoryModal episode={story} spirit={spirit} onClose={() => setStory(null)} onFinish={() => finishStory(story)} />}{postStory && <PostStoryModal episode={postStory} spirit={spirit} onFinish={() => finishPost(postStory)} />}{learning && pack && <LearningModal pack={pack} onClose={() => setLearning(false)} onAnswer={learningResult} />}{battle && <BattleModal episode={battle} spirit={spirit} save={save} onClose={() => setBattle(null)} onAnswer={learningResult} onSwap={() => update(s => recordEp07Swap(s))} onBossPhase={phase => update(s => setEp10BossPhase(s, phase))} onWin={() => winBattle(battle)} />}
    {approach && <CompanionApproachModal stage={save.episodeState.ep06.approachStage} onStage={stage => update(s => setEp06ApproachStage(s, stage))} onConfirm={() => { setApproach(false); update(s => { const acquired = completeEpisode(confirmEp06Companion(s), 6); return acquired.starter ? grantResonanceMilestone(acquired, 'ep06.companion_join', [acquired.starter, 'MIST_PORT_SPIRIT_01'], 3) : acquired; }); notify('共鸣发生了明显变化'); track('episode_completed', { episode: 6 }); }} />}{monument && <MonumentModal state={save} onFace={face => update(s => setEp08MonumentFace(s, face))} onClue={clue => update(s => recordEp08Clue(s, clue))} onComplete={() => { setMonument(false); update(s => completeEpisode(recordEp08Clue(recordEp08Clue(s, 'residue'), 'position'), 8)); track('episode_completed', { episode: 8 }); }} onArena={() => setArena(true)} />}{tracking && <TrackingModal state={save} onAction={slot => update(s => recordEp09TrackingAction(s, slot))} onAnswer={learningResult} onComplete={() => { setTracking(false); setBattle(9); }} />}{sky && <SkySilhouetteModal onComplete={() => { setSky(false); update(s => completeEpisode(recordEp09SkySilhouette(setEp09RareClueCount(s, 1)), 9)); track('episode_completed', { episode: 9 }); }} />}
    {arena && <ArenaModal onClose={() => setArena(false)} onComplete={() => { update(s => s.episodeState.ep08.arenaSnapshotCompleted ? s : completeEp08ArenaSnapshot({ ...s, exploration: s.exploration + 4 })); setArena(false); notify('竞技快照已记录'); }} />}{codex && <CodexModal save={save} spirit={spirit} onClose={() => setCodex(false)} />}{toast && <div className="toast">{toast}</div>}{process.env.NODE_ENV === 'development' && <DevPanel save={save} onApply={applyDevPreset} onReplaceSave={setSave} onClear={() => { clearGameSave(); setSave(createEmptySave()); }} />}</main>;
}

function OpeningPrologueModal({ index, interaction, onProgress, onFinish }: { index: number; interaction: OpeningInteraction; onProgress: (index: number) => void; onFinish: () => void }) { const safe = Math.min(index, OPENING_PROLOGUE.length - 1), line = OPENING_PROLOGUE[safe]; const next = () => { if (interaction) onProgress(safe + 1); else if (safe === 3 || safe === 8) onProgress(safe); else if (safe < OPENING_PROLOGUE.length - 1) onProgress(safe + 1); else onFinish(); }; useEffect(() => { track('opening_prologue_started'); }, []); if (interaction) { const copy = OPENING_INTERACTIONS[interaction]; return <main className="starter-screen opening-screen"><section className="story-modal opening-modal opening-interaction"><span>序章 · {interaction === 'luggage' ? '码头边' : '旧渡口边'}</span><div className="story-stage"><div className="scene-symbol opening-scene opening-interaction-scene">{interaction === 'luggage' ? '木板' : '脚印'}</div><div><b>{copy.label}</b><p>{copy.text}</p></div></div><button className="story-next" onClick={next}>{copy.action}</button></section></main>; } return <main className="starter-screen opening-screen"><section className="story-modal opening-modal"><span>序章 · 雾港</span><div className="story-stage"><div className="scene-symbol opening-scene">{safe < 5 ? '码头' : safe < 10 ? '旧渡口' : '语灵站'}</div><div><b>{line[0]}</b><p>{line[1]}</p></div></div><button className="story-next" onClick={next}>{safe < OPENING_PROLOGUE.length - 1 ? '继续' : '进入语灵站'}</button></section></main>; }

function StarterStationGate({ stage, onProgress, onChoose }: { stage: number; onProgress: (stage: number) => void; onChoose: (starter: Starter) => void }) { const behavior = STARTER_BEHAVIORS[Math.min(stage, STARTER_BEHAVIORS.length - 1)], spirit = spiritFor(behavior.starter); if (stage < STARTER_BEHAVIORS.length) return <main className="starter-screen station-screen"><section className="story-modal station-modal"><span>序章 · 语灵站　观察 {stage + 1}/3</span><div className={`story-stage station-behavior ${spirit.tone}`}><div className="starter-art"><img className="spirit-art" src={spirit.image} alt={spirit.name} /></div><div><b>{spirit.name}</b><p>{behavior.text}</p><small>{behavior.detail}</small></div></div><button className="story-next" onClick={() => onProgress(stage + 1)}>{stage < 2 ? '继续观察' : '看看它们愿不愿意跟你走'}</button></section></main>; return <StarterGate onChoose={onChoose} />; }
function StarterGate({ onChoose }: { onChoose: (starter: Starter) => void }) { return <main className="starter-screen"><section className="starter-dialogue"><span>序章 · 语灵站</span><h1>{STARTER_SELECTION_UI.title}</h1><p>{STARTER_SELECTION_UI.prompt}</p></section><section className="starter-grid">{SPIRITS.map(spirit => <article className={`starter-card ${spirit.tone}`} key={spirit.name}><div className="starter-art"><img className="spirit-art" src={spirit.image} alt={spirit.name} /></div><h2>{spirit.name}</h2><p>{STARTER_CHOICE_REACTIONS[spirit.name]}</p><button onClick={() => onChoose(spirit.name)}>我想和{spirit.name}一起走</button></article>)}</section><small className="starter-note">{STARTER_SELECTION_UI.note}</small></main>; }
function EpisodeButton({ episode, open, done, onClick }: { episode: Episode; open: boolean; done: boolean; onClick: () => void }) { return <button className={done ? 'done' : ''} disabled={!open || done} onClick={onClick}><i>{done ? '✓' : episode}</i><span>EP{String(episode).padStart(2, '0')} · {placeFor(episode)}<b>{titleFor(episode)}</b></span><em>{done ? '已完成' : open ? '进入' : '未解锁'}</em></button>; }
function StoryModal({ episode, spirit, onClose, onFinish }: { episode: Episode; spirit: SpiritConfig; onClose: () => void; onFinish: () => void }) { const lines = STORIES[episode] ?? ([['[PENDING_K3]', '[PENDING_K3]']] as const); const [index, setIndex] = useState(0), line = lines[Math.min(index, lines.length - 1)], visual = episode === 4 ? '尾' : episode === 8 ? '碑' : episode === 9 ? '稀' : episode === 10 ? '守' : null; return <div className="modal-backdrop"><section className="story-modal"><button className="close" onClick={onClose}>×</button><span>EP{String(episode).padStart(2, '0')} · {placeFor(episode)}</span><div className="story-stage">{visual ? <div className={`scene-symbol scene-${episode}`}>{visual}</div> : <img src={spirit.image} alt={spirit.name} />}<div><b>{line[0]}</b><p>{line[1]}</p></div></div><button className="story-next" onClick={() => index < lines.length - 1 ? setIndex(index + 1) : onFinish()}>{index < lines.length - 1 ? '继续' : EPISODE_CONFIG[episode].hasBattle ? '进入战斗' : '继续'}</button></section></div>; }
function LinearStoryModal({ label, lines, spirit, bonding = false, onFinish }: { label: string; lines: readonly Line[]; spirit: SpiritConfig; bonding?: boolean; onFinish: () => void }) { const [index, setIndex] = useState(0), line = lines[Math.min(index, lines.length - 1)], bond = bonding && index === 0; return <div className="modal-backdrop intro-backdrop"><section className="story-modal"><span>{label}</span><div className="story-stage"><img src={spirit.image} alt={spirit.name} /><div><b>{bond ? spirit.name : line[0]}</b><p>{bond ? BONDING[spirit.name] : line[1]}</p></div></div><button className="story-next" onClick={() => index < lines.length - 1 ? setIndex(index + 1) : onFinish()}>{index < lines.length - 1 ? '继续' : '前往港外旧路'}</button></section></div>; }
function Ep1TutorialModal({ index, onAnswer, onProgress }: { index: number; onAnswer: (correct: boolean, seen: boolean, question: LearningQuestion) => void; onProgress: (index: number) => void }) {
  const questions = getFirstPackQuestions().slice(0, 3), question = questions[Math.min(index, 2)];
  const [feedback, setFeedback] = useState(''); const started = useRef(0);
  useEffect(() => { track('lesson_started', { packId: 'EP01_TUTORIAL' }); started.current = Date.now(); }, []);
  function answer(choice: string) { const store = loadLearningStore(); const seen = (store.progress[question.wordId]?.attempts ?? 0) > 0; const correct = choice === question.answer; recordLearningAnswer(question, correct, Date.now() - started.current); track('question_answered', { wordId: question.wordId, layer: 'L1', correct, source: 'ep01_tutorial' }); onAnswer(correct, seen, question); setFeedback(correct ? '它回应了你的声音。' : `正确义项：${question.answer}`); window.setTimeout(() => { setFeedback(''); onProgress(index + 1); started.current = Date.now(); }, 650); }
  return <div className="modal-backdrop intro-backdrop"><section className="learn-sheet ep1-tutorial"><span>EP01 · 第一次真正认识　{index + 1}/3</span><h2>{question.word}</h2><i>{question.phonetic}</i><p>{question.prompt}</p><div>{question.choices.map(choice => <button key={choice} disabled={!!feedback} onClick={() => answer(choice)}>{choice}</button>)}</div>{feedback && <strong>{feedback}</strong>}<small>完成3个L1后剧情会在语灵站内继续，不跳回首页。</small></section></div>;
}

function LearningModal({ pack, onClose, onAnswer }: { pack: ReturnType<typeof getCurrentLearningPack>; onClose: () => void; onAnswer: (correct: boolean, seen: boolean, question: LearningQuestion) => void }) {
  const [index, setIndex] = useState(Math.min(pack.learned, pack.questions.length - 1)); const [feedback, setFeedback] = useState(''); const started = useRef(0); const question = pack.questions[index];
  useEffect(() => { track('lesson_started', { packId: pack.id }); started.current = Date.now(); }, [pack.id]);
  function answer(choice: string) { const seen = index < pack.learned; const correct = choice === question.answer; recordLearningAnswer(question, correct, Date.now() - started.current); track('question_answered', { wordId: question.wordId, layer: question.layer, correct, source: 'lesson' }); onAnswer(correct, seen, question); setFeedback(correct ? '记住了。探索力正在汇聚。' : `正确义项：${question.answer}`); window.setTimeout(() => { setFeedback(''); if (index < pack.questions.length - 1) { setIndex(index + 1); started.current = Date.now(); } else { onClose(); } }, 650); }
  return <div className="modal-backdrop"><section className="learn-sheet"><button className="close" onClick={onClose}>×</button><span>{pack.id} · L1　{index + 1}/{pack.questions.length}</span><h2>{question.word}</h2><i>{question.phonetic}</i><p>{question.prompt}</p><div>{question.choices.map(choice => <button key={choice} disabled={!!feedback} onClick={() => answer(choice)}>{choice}</button>)}</div>{feedback && <strong>{feedback}</strong>}</section></div>;
}

type BattleProps = { episode: Episode; spirit: SpiritConfig; save: GameSave; onClose: () => void; onAnswer: (correct: boolean, seen: boolean, question: LearningQuestion, activeSpiritId?: string) => void; onSwap: () => void; onBossPhase: (phase: 1 | 2 | 3) => void; onWin: () => void };
function BattleModal({ episode, spirit, save, onClose, onAnswer, onSwap, onBossPhase, onWin }: BattleProps) {
  const boss = episode === 10, requiresSwap = episode === 7, initialEnemy = boss ? 72 : episode === 9 ? 120 : requiresSwap ? 96 : 100;
  const battleId = `battle.ep${String(episode).padStart(2, '0')}`;
  const makeTeam = () => createTeamBattleState({ battleId: 'battle.ep07.team_test', spirits: [{ id: spirit.name, maxHp: 100, tacticalTags: ['assault'] }, { id: 'MIST_PORT_SPIRIT_01', maxHp: 112, tacticalTags: ['guard'] }], enemy: { id: 'EP07_TARGET', maxHp: 96, nextAttack: { kind: 'heavy', damage: 34 } } });
  const [enemy, setEnemy] = useState(initialEnemy), [ally, setAlly] = useState(100), [teamBattle, setTeamBattle] = useState<TeamBattleState>(makeTeam), [phase, setPhase] = useState<1 | 2 | 3>(1), [question, setQuestion] = useState<LearningQuestion | null>(null), [skill, setSkill] = useState(spirit.skills[0]), [message, setMessage] = useState('[PENDING_K3]'), [wrongId, setWrongId] = useState<string>(), [wrongStreak, setWrongStreak] = useState(0), [defeated, setDefeated] = useState(false);
  const outcome = useRef<'active' | 'won' | 'defeated'>('active'); const started = useRef(0); const timer = useRef<number | null>(null);
  function battleLog(input: Omit<BattleLogEventInput, 'battleId'>) { if (process.env.NODE_ENV === 'development') appendBattleLog({ battleId, ...input }); }
  useEffect(() => { if (process.env.NODE_ENV === 'development') appendBattleLog({ battleId, turn: 1, activeSpirit: spirit.name, enemyAttackKind: requiresSwap ? 'heavy' : 'normal', battleResult: 'start' }); return () => { if (timer.current) window.clearTimeout(timer.current); if (outcome.current === 'active' && process.env.NODE_ENV === 'development') appendBattleLog({ battleId, battleResult: 'aborted' }); }; }, [battleId, requiresSwap, spirit.name]);
  const playerCeiling: MasteryLayer = 'L1', approved: MasteryLayer = 'L1'; const displayedLayer = boss ? resolveBossQuestionLayer(phaseCapForBoss(phase), playerCeiling, approved) : 'L1'; const teamSize = save.episodeState.ep06.teamSpiritIds.length || (save.companion ? 2 : 1);
  const activeTeamSpirit = getActiveSpirit(teamBattle), reserveTeamSpirit = getReserveSpirits(teamBattle)[0], swapCue = requiresSwap ? getSwapCue(teamBattle, reserveTeamSpirit?.id) : null;
  function chooseSkill(nextSkill: typeof skill) { if (outcome.current !== 'active') return; if (requiresSwap && activeTeamSpirit.status === 'down') { setMessage('当前伙伴无法继续行动，请换位'); return; } setSkill(nextSkill); setQuestion(getDueQuestion(wrongId) ?? getFirstPackQuestions()[0] ?? null); started.current = Date.now(); }
  function swap() { if (!requiresSwap || !reserveTeamSpirit || !getSwapAvailability(teamBattle, reserveTeamSpirit.id).allowed) return; const from = activeTeamSpirit.id, to = reserveTeamSpirit.id; setTeamBattle(current => swapActiveSpirit(current, to)); onSwap(); battleLog({ turn: teamBattle.turn, activeSpirit: to, enemyAttackKind: teamBattle.enemy.nextAttack.kind, swap: { from, to, reason: swapCue?.reason }, battleResult: 'turn' }); setMessage(to === 'MIST_PORT_SPIRIT_01' ? '绒岚成为当前承伤伙伴 · 本回合不出题' : `${to}回到场上 · 攻击伤害30（绒岚24）`); }
  function retry() { setEnemy(initialEnemy); setAlly(100); setTeamBattle(makeTeam()); setPhase(1); setQuestion(null); setSkill(spirit.skills[0]); setWrongId(undefined); setWrongStreak(0); setDefeated(false); setMessage('[PENDING_K3]'); outcome.current = 'active'; battleLog({ turn: 1, activeSpirit: spirit.name, enemyAttackKind: requiresSwap ? 'heavy' : 'normal', battleResult: 'start' }); }
  function resolveTeamDefense(current: TeamBattleState) { const attack = current.enemy.nextAttack.kind === 'heavy' ? { kind: 'normal' as const, damage: 18 } : { kind: 'heavy' as const, damage: 34 }; return setNextEnemyAttack(resolveEnemyTurn(current), attack); }
  function answer(choice: string) {
    if (!question || outcome.current !== 'active') return;
    const correct = choice === question.answer;
    const store = loadLearningStore();
    const seen = (store.progress[question.wordId]?.attempts ?? 0) > 0;
    const activeSpiritId = requiresSwap ? activeTeamSpirit.id : spirit.name;
    recordLearningAnswer(question, correct, Date.now() - started.current);
    track('question_answered', { wordId: question.wordId, layer: question.layer, correct, source: `battle_ep${episode}` });
    onAnswer(correct, seen, question, activeSpiritId);
    setQuestion(null);
    if (requiresSwap) {
      const before = teamBattle;
      const beforeActive = getActiveSpirit(before);
      const attack = before.enemy.nextAttack;
      let nextTeam = before;
      if (correct) nextTeam = applyTeamTactic(nextTeam, { kind: 'damage', amount: beforeActive.id === 'MIST_PORT_SPIRIT_01' ? 24 : 30 });
      nextTeam = resolveTeamDefense(nextTeam);
      const afterActive = nextTeam.spirits[beforeActive.id];
      const damageTaken = Math.max(0, beforeActive.hp - afterActive.hp);
      const damageDealt = Math.max(0, before.enemy.hp - nextTeam.enemy.hp);
      const shieldAbsorbed = Math.max(0, beforeActive.shield - afterActive.shield);
      const reduced = before.enemy.incomingDamageReductionTurns > 0 ? Math.max(0, attack.damage - damageTaken - shieldAbsorbed) : 0;
      setTeamBattle(nextTeam);
      setEnemy(nextTeam.enemy.hp);
      battleLog({ turn: before.turn, activeSpirit: beforeActive.id, enemyAttackKind: attack.kind, shield: shieldAbsorbed, reduction: reduced, questionResult: correct ? 'correct' : 'incorrect', wordId: question.wordId, damageTaken, damageDealt, battleResult: nextTeam.result === 'won' ? 'victory' : nextTeam.result === 'lost' ? 'defeat' : 'turn' });
      const readableName = beforeActive.id === 'MIST_PORT_SPIRIT_01' ? '绒岚' : beforeActive.id;
      const defenseFeedback = shieldAbsorbed > 0 ? `护盾吸收${shieldAbsorbed}，HP仅-${damageTaken}` : reduced > 0 ? `削弱减伤${reduced}，HP-${damageTaken}` : `承受${damageTaken}伤害`;
      if (nextTeam.result === 'won') { outcome.current = 'won'; setMessage(`${readableName}造成${damageDealt}伤害 · 战斗结束`); timer.current = window.setTimeout(onWin, 350); }
      else if (nextTeam.result === 'lost') { outcome.current = 'defeated'; setDefeated(true); setMessage(`${readableName}${defenseFeedback} · 队伍无法继续`); }
      else setMessage(`${readableName}${defenseFeedback} · ${correct ? `造成${damageDealt}伤害` : '本回合未造成伤害'}`);
      return;
    }
    if (!correct) {
      const streak = wrongStreak + 1;
      const damageTaken = boss ? 22 : 16;
      const hp = Math.max(0, ally - damageTaken);
      setWrongId(question.wordId);
      setWrongStreak(streak);
      setAlly(hp);
      battleLog({ turn: wrongStreak + 1, activeSpirit: spirit.name, enemyAttackKind: 'normal', questionResult: 'incorrect', wordId: question.wordId, damageTaken, damageDealt: 0, battleResult: hp === 0 ? 'defeat' : 'turn' });
      setMessage(streak >= 2 ? '[PENDING_K3] · 题层降至L1' : `错误：${question.word} · FSRS已重新调度`);
      if (hp === 0) { outcome.current = 'defeated'; setDefeated(true); }
      return;
    }
    setWrongId(undefined);
    setWrongStreak(0);
    const damage = skill.name === '焰尾' ? 42 : 20;
    const next = Math.max(0, enemy - damage);
    if (next > 0) { setEnemy(next); battleLog({ activeSpirit: spirit.name, enemyAttackKind: 'none', questionResult: 'correct', wordId: question.wordId, damageTaken: 0, damageDealt: damage, battleResult: 'turn' }); setMessage(`L1 · ${skill.name} · [PENDING_K3]`); return; }
    if (boss && phase < 3) { const nextPhase = (phase + 1) as 1 | 2 | 3; setPhase(nextPhase); setEnemy(initialEnemy); onBossPhase(nextPhase); battleLog({ activeSpirit: spirit.name, enemyAttackKind: 'none', questionResult: 'correct', wordId: question.wordId, damageDealt: damage, battleResult: 'turn' }); setMessage(`[PENDING_K3] · Phase ${nextPhase} · ${bossQuestionLayer(save, 'L1', 'L1')}`); return; }
    outcome.current = 'won';
    setEnemy(0);
    battleLog({ activeSpirit: spirit.name, enemyAttackKind: 'none', questionResult: 'correct', wordId: question.wordId, damageDealt: damage, battleResult: 'victory' });
    timer.current = window.setTimeout(onWin, 350);
  }
  function companionTactic(kind: 'cover' | 'soften') { if (!requiresSwap || activeTeamSpirit.id !== 'MIST_PORT_SPIRIT_01' || question) return; setTeamBattle(current => applyTeamTactic(current, MIST_PORT_TACTICS[kind])); setMessage(kind === 'cover' ? '绒岚准备护盾' : '绒岚准备削弱下一次攻击'); setQuestion(getDueQuestion(wrongId) ?? getFirstPackQuestions()[0] ?? null); started.current = Date.now(); }
  const teamStatus = requiresSwap ? <div className="team-battle-status">{Object.values(teamBattle.spirits).map(member => { const active = member.id === teamBattle.activeSpiritId; return <div className={active ? 'active' : ''} key={member.id}><b>{member.id === 'MIST_PORT_SPIRIT_01' ? '绒岚' : member.id}<em>{active ? '当前承伤' : '后备'}</em></b><small>HP {member.hp}/{member.maxHp} · 护盾 {member.shield}</small></div>; })}<small className={teamBattle.enemy.nextAttack.kind === 'heavy' ? 'heavy-warning' : ''}>敌方下一击：{teamBattle.enemy.nextAttack.kind === 'heavy' ? '重击' : '普通攻击'} · 换位冷却 {teamBattle.swapCooldownRemaining}</small>{swapCue && <strong>换位提示：{swapCue.reason === 'target_guards_heavy_attack' ? '绒岚更适合承受下一次重击' : '当前伙伴血量过低'}</strong>}</div> : null;
  const body = defeated ? <div className="battle-skills battle-defeat"><button onClick={retry}><b>重新挑战</b><small>保留已记录的学习结果</small></button><button onClick={onClose}><b>暂时退出</b><small>当前剧情节点未完成</small></button></div> : question ? <div className="battle-question"><h3>{question.word}</h3><small>{question.phonetic} · {displayedLayer}</small>{question.choices.map(choice => <button key={choice} onClick={() => answer(choice)}>{choice}</button>)}</div> : <div className="battle-skills">{spirit.skills.map(item => <button key={item.name} onClick={() => chooseSkill(item)}><b>{item.name}</b><small>{item.effect}</small></button>)}{requiresSwap && activeTeamSpirit.id === 'MIST_PORT_SPIRIT_01' && <><button onClick={() => companionTactic('cover')}><b>覆护</b><small>获得18点护盾 · 不绑定题层</small></button><button onClick={() => companionTactic('soften')}><b>缓冲</b><small>降低下一次伤害 · 不绑定题层</small></button></>}{requiresSwap && teamSize >= 2 && reserveTeamSpirit && <button className={swapCue ? 'swap-cue' : ''} onClick={swap} disabled={!getSwapAvailability(teamBattle, reserveTeamSpirit.id).allowed}><b>换位至 {reserveTeamSpirit.id === 'MIST_PORT_SPIRIT_01' ? '绒岚' : reserveTeamSpirit.id}</b><small>{reserveTeamSpirit.id === 'MIST_PORT_SPIRIT_01' ? '承受重击更稳' : '攻击30，高于绒岚的24'} · 冷却 {teamBattle.swapCooldownRemaining}</small></button>}</div>;
  return <div className="modal-backdrop"><section className="p0-battle"><button className="close" onClick={onClose}>×</button><span>EP{String(episode).padStart(2, '0')} · {boss ? `Boss · Phase ${phase}` : episode === 9 ? '稀有试探战' : episode === 7 ? '双伙伴战斗' : '探索战斗'}</span><h2>{boss ? 'EP10 · [PENDING_K3]' : titleFor(episode)}</h2>{teamStatus}<div className="battle-health"><b>{requiresSwap ? `${activeTeamSpirit.id === 'MIST_PORT_SPIRIT_01' ? '绒岚' : activeTeamSpirit.id} ${activeTeamSpirit.hp}` : `${spirit.name} ${ally}`}</b><b>目标 {enemy}</b></div><div className="battle-figures"><div className="battle-team-visual"><img src={spirit.image} alt={spirit.name} />{teamSize >= 2 && <div className="unknown-fighter">绒</div>}</div><strong>VS</strong><div className={`shadow-foe ${boss ? 'gatekeeper' : ''}`}>{boss ? '守' : episode === 9 ? '稀' : '蚀'}</div></div><p>{message}</p>{body}<small className="battle-rule">题层：{displayedLayer} · FSRS只负责调度；战术与题层解绑。</small></section></div>;
}
function CompanionApproachModal({ stage, onStage, onConfirm }: { stage: ApproachStage; onStage: (stage: ApproachStage) => void; onConfirm: () => void }) { const complete = stage >= 3, next = Math.min(3, stage + 1) as ApproachStage; return <div className="modal-backdrop"><section className="skeleton-modal"><span>EP06 · interaction {stage}/3</span><h2>绒岚 · [PENDING_K3]</h2><p>[PENDING_K3]</p><div className="skeleton-steps">{[1, 2, 3].map(step => <i className={stage >= step ? 'active' : ''} key={step}>interaction_{step}</i>)}</div>{complete ? <button className="story-next" onClick={onConfirm}>确认获得 MIST_PORT_SPIRIT_01</button> : <button className="story-next" onClick={() => onStage(next)}>完成 interaction {next}</button>}</section></div>; }
function MonumentModal({ state, onFace, onClue, onComplete, onArena }: { state: GameSave; onFace: (face: 'front' | 'back') => void; onClue: (clue: 'residue' | 'position') => void; onComplete: () => void; onArena: () => void }) { const monument = state.episodeState.ep08, ready = monument.residueRecorded && monument.positionRecorded; return <div className="modal-backdrop"><section className="skeleton-modal"><span>EP08 · unnamed monument</span><h2>无名碑 · [PENDING_K3]</h2><div className="skeleton-actions"><button className={monument.monumentFace === 'front' ? 'active' : ''} onClick={() => onFace('front')}>查看正面</button><button className={monument.monumentFace === 'back' ? 'active' : ''} onClick={() => onFace('back')}>查看背面</button><button disabled={monument.residueRecorded} onClick={() => onClue('residue')}>记录残字</button><button disabled={monument.positionRecorded} onClick={() => onClue('position')}>记录位置</button></div><p>[PENDING_K3]</p><div className="skeleton-status">残字 {monument.residueRecorded ? '✓' : '—'}　位置 {monument.positionRecorded ? '✓' : '—'}</div>{monument.arenaUnlocked && <button className="skeleton-subaction" onClick={onArena}>竞技快照（可选）</button>}<button className="story-next" disabled={!ready} onClick={onComplete}>完成记录并继续</button></section></div>; }
function TrackingModal({ state, onAction, onAnswer, onComplete }: { state: GameSave; onAction: (slot: TrackingSlotId) => void; onAnswer: (correct: boolean, seen: boolean, question: LearningQuestion) => void; onComplete: () => void }) {
  const slots: TrackingSlotId[] = ['tracking_01', 'tracking_02', 'tracking_03'];
  const complete = slots.every(slot => state.episodeState.ep09.tracking[slot].completed);
  const [activeSlot, setActiveSlot] = useState<TrackingSlotId | null>(null);
  const [question, setQuestion] = useState<LearningQuestion | null>(null);
  const started = useRef(0);
  function start(slot: TrackingSlotId) { setActiveSlot(slot); setQuestion(getDueQuestion() ?? getFirstPackQuestions()[0] ?? null); started.current = Date.now(); }
  function answer(choice: string) { if (!question || !activeSlot) return; const store = loadLearningStore(), correct = choice === question.answer, seen = (store.progress[question.wordId]?.attempts ?? 0) > 0; recordLearningAnswer(question, correct, Date.now() - started.current); track('question_answered', { wordId: question.wordId, layer: 'L1', correct, source: `ep09_${activeSlot}` }); onAnswer(correct, seen, question); onAction(activeSlot); setActiveSlot(null); setQuestion(null); }
  if (question && activeSlot) return <div className="modal-backdrop"><section className="skeleton-modal"><span>EP09 · {activeSlot} · L1</span><h2>{question.word}</h2><p>{question.prompt}</p><div className="tracking-question">{question.choices.map(choice => <button key={choice} onClick={() => answer(choice)}>{choice}</button>)}</div></section></div>;
  return <div className="modal-backdrop"><section className="skeleton-modal"><span>EP09 · tracking slots</span><h2>雾坡 · [PENDING_K3]</h2><p>每处只进行一次必要英语行动。</p><div className="tracking-grid">{slots.map(slot => { const item = state.episodeState.ep09.tracking[slot]; return <button key={slot} disabled={item.completed} onClick={() => start(slot)}><b>{slot}</b><small>{item.completed ? 'L1 action ✓' : '执行1次L1 action'}</small></button>; })}</div><button className="story-next" disabled={!complete} onClick={onComplete}>进入稀有试探战</button></section></div>;
}
function SkySilhouetteModal({ onComplete }: { onComplete: () => void }) { return <div className="modal-backdrop"><section className="skeleton-modal"><span>EP09 · sky silhouette</span><h2>SKY_LEGEND_01</h2><p>[PENDING_K3]</p><div className="sky-placeholder">翼</div><button className="story-next" onClick={onComplete}>记录天空剪影</button></section></div>; }
function PostStoryModal({ episode, spirit, onFinish }: { episode: Episode; spirit: SpiritConfig; onFinish: () => void }) { const lines = POST_STORIES[episode] ?? ([['[PENDING_K3]', '[PENDING_K3]']] as const), [index, setIndex] = useState(0), line = lines[Math.min(index, lines.length - 1)]; return <div className="modal-backdrop"><section className="story-modal"><span>EP{String(episode).padStart(2, '0')} · 战后</span><div className="story-stage">{episode === 10 ? <div className="scene-symbol scene-10">守</div> : <img src={spirit.image} alt={spirit.name} />}<div><b>{line[0]}</b><p>{line[1]}</p></div></div><button className="story-next" onClick={() => index < lines.length - 1 ? setIndex(index + 1) : onFinish()}>{index < lines.length - 1 ? '继续' : '完成剧情'}</button></section></div>; }
function ArenaModal({ onClose, onComplete }: { onClose: () => void; onComplete: () => void }) { const [round, setRound] = useState(0); return <div className="modal-backdrop"><section className="story-modal arena-modal"><button className="close" onClick={onClose}>×</button><span>旧擂台 · 测试快照</span><h2>[PENDING_K3]</h2><p>当前仅为本地测试快照，不是真实异步竞技。</p><div className="arena-snapshot"><b>攻击</b><span>当前作答结果</span><b>防守/反击</b><span>历史掌握快照</span></div><button className="story-next" onClick={() => round < 2 ? setRound(round + 1) : onComplete()}>{round < 2 ? `完成模拟回合 ${round + 1}/3` : '结束首场竞技'}</button></section></div>; }
function ChapterMap({ save }: { save: GameSave }) { const hooks = save.episodeState.ep10.hookFlags; return <section className="chapter-map"><span>章末地图 · 数据状态</span><h2>[PENDING_K3]</h2><div><i>map.harbor</i><i>map.unnamed_outline</i><i>map.next_outline</i></div><ul><li>starter_evolution: {hooks.starterEvolution ? 'ready' : 'pending'}</li><li>MIST_PORT_RARE_01 · {save.episodeState.ep09.rareClueCount}/3</li><li>SKY_LEGEND_01 · {hooks.skyLegend ? 'recorded' : 'pending'}</li></ul></section>; }
function CodexModal({ save, spirit, onClose }: { save: GameSave; spirit: SpiritConfig; onClose: () => void }) { return <div className="modal-backdrop"><section className="story-modal codex-modal"><button className="close" onClick={onClose}>×</button><span>雾港图鉴</span><h2>见过的语灵</h2><div className="codex-list"><article><img src={spirit.image} alt={spirit.name} /><b>{spirit.name}</b><small>初伴 · 已共鸣 · 下一形态？？？</small></article><article><div className="unknown-mini">?</div><b>{save.sightings > 0 ? '绒岚' : '？？？'}</b><small>{save.sightings > 0 ? `MIST_PORT_SPIRIT_01 · ${save.companion ? '已共鸣' : `未共鸣 · 目击 ${save.sightings}/3`}` : '尚未见过'}</small></article><article><div className="rare-mini">稀</div><b>{save.rareSeen ? '未记录稀客' : '？？？'}</b><small>{save.rareSeen ? `未共鸣 · 线索${save.episodeState.ep09.rareClueCount}/3` : '尚未见过'}</small></article><article><div className="sky-mini">翼</div><b>天空剪影</b><small>{save.episodeState.ep09.skySilhouetteSeen ? 'SKY_LEGEND_01 · 已记录' : '尚未记录'}</small></article></div></section></div>; }
