import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {initialLeaf,leafReducer as reduce,LEAF_SKILLS,LEAF_MOTION,type LeafState,type LeafId} from '../app/prototype/battle-ui/leaf-model.ts';
let n=0;function test(label:string,fn:()=>void){fn();console.log(`PASS ${++n}: ${label}`);}
const cast=(s:LeafState,id:LeafId)=>reduce(reduce(s,{type:'select',id}),{type:'cast'});
const finish=(s:LeafState)=>{for(let i=0;i<3&&!['won','lost','choose'].includes(s.phase);i++)s=reduce(s,{type:'advance'});return s;};
test('48/60 baseline',()=>{assert.equal(initialLeaf().playerHp,48);assert.equal(initialLeaf().enemyHp,60);});
test('exact existing effects',()=>assert.deepEqual(LEAF_SKILLS.map(s=>[s.damage,s.shield,s.mitigation]),[[24,0,0],[8,24,0],[0,0,.4]]));
test('select does not cast',()=>{const s=reduce(initialLeaf(),{type:'select',id:'ward'});assert.equal(s.shield,0);assert.equal(s.enemyHp,60);});
test('leaf slap damage24',()=>assert.equal(cast(initialLeaf(),'slap').enemyHp,36));
test('ward atomic damage8 plus shield24 no heal',()=>{const s=cast(initialLeaf(),'ward');assert.equal(s.enemyHp,52);assert.equal(s.shield,24);assert.equal(s.playerHp,48);});
test('double cast ignored',()=>{const s=cast(initialLeaf(),'ward');assert.equal(reduce(s,{type:'cast'}),s);});
test('shield absorbs before HP',()=>{const s=finish(cast(initialLeaf(),'ward'));assert.equal(s.playerHp,48);assert.equal(s.shield,10);assert.equal(s.absorbed,14);});
test('residual shield carries and adds',()=>assert.equal(cast(finish(cast(initialLeaf(),'ward')),'ward').shield,34));
test('root no attack no healing',()=>{const s=cast({...initialLeaf(),playerHp:30},'root');assert.equal(s.playerHp,30);assert.equal(s.enemyHp,60);assert.equal(s.mitigation,.4);});
test('14 reduced40 rounds8',()=>{const s=finish(cast(initialLeaf(),'root'));assert.equal(s.playerHp,40);assert.equal(s.prevented,6);assert.equal(s.mitigation,0);});
test('28 reduced40 rounds17 then shield10 then HP7',()=>{const s=finish(cast({...initialLeaf(),turn:2,shield:10},'root'));assert.equal(s.playerHp,41);assert.equal(s.absorbed,10);assert.equal(s.prevented,11);assert.equal(s.shield,0);});
test('kill skips enemy',()=>{const s=finish(cast({...initialLeaf(),enemyHp:8},'ward'));assert.equal(s.phase,'won');assert.equal(s.playerHp,48);});
test('loss waits until enemy result',()=>{let s=cast({...initialLeaf(),playerHp:2},'slap');s=reduce(reduce(s,{type:'advance'}),{type:'advance'});assert.equal(s.phase,'enemy');assert.equal(s.playerHp,0);assert.equal(reduce(s,{type:'advance'}).phase,'lost');});
test('reset all states',()=>assert.deepEqual(reduce(cast(initialLeaf(),'ward'),{type:'reset'}),initialLeaf()));
test('three slaps can win',()=>{let s=initialLeaf();for(let i=0;i<3;i++)s=finish(cast(s,'slap'));assert.equal(s.phase,'won');assert.equal(s.playerHp,6);});
test('all motions reserve readable result',()=>{for(const m of Object.values(LEAF_MOTION))assert.ok(m.durationMs-m.impactMs>=1200);});
test('bounded legal paths HP shield invariants',()=>{let q=[initialLeaf()];for(let depth=0;depth<7;depth++){const next:LeafState[]=[];for(const s of q)for(const skill of LEAF_SKILLS){const r=finish(cast(s,skill.id));assert.ok(r.playerHp>=0&&r.playerHp<=48);assert.ok(r.enemyHp>=0&&r.enemyHp<=60);assert.ok(r.shield>=0&&Number.isInteger(r.shield));if(r.phase==='choose')next.push(r);}q=next;}});
const page=readFileSync('app/prototype/battle-ui/page.tsx','utf8'),ui=readFileSync('app/prototype/battle-ui/leaf-battle.tsx','utf8'),css=readFileSync('app/prototype/battle-ui/leaf-battle.css','utf8');
test('same entry default water preserved',()=>{assert.ok(page.includes("useState<'lange' | 'jinwei' | 'yayu'>('lange')"));assert.ok(page.includes("spirit === 'yayu' ? <LeafBattle/>"));});
test('HP and shield withhold until impact',()=>{assert.ok(ui.includes("pending&&s.phase==='enemy'?s.previousPlayerHp"));assert.ok(ui.includes('const shield=pending?s.previousShield:s.shield'));assert.ok(ui.includes('护盾吸收'));});
test('timers and decode guard cleanup',()=>{assert.ok(ui.includes('clearTimeout(timer)'));assert.ok(ui.includes('cancelled=true'));assert.ok(ui.includes('!choosing||!ready'));});
test('reduced motion static and per-frame clips',()=>{assert.ok(css.includes('prefers-reduced-motion:reduce'));assert.ok(ui.includes('clipPath={`url(#${id})`}'));assert.ok(css.includes('.yl-idle { opacity:1!important; }'));});
test('no learning or saves',()=>assert.doesNotMatch(ui,/localStorage|sessionStorage|battleEligible|fsrs/));
console.log(`Yayu ${n}/${n} PASS; not browser playtest`);
