import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { BOSS_SKILLS, DEMO_RULES, DEMO_SKILLS, demoReducer, getEnemySkill, initialDemo, previewIncoming, type DemoState, type SkillId } from '../app/prototype/battle-ui/demo-model.ts';
import { activeMotion, BOSS_MOTION, displayedHp, motionKey, PLAYER_MOTION } from '../app/prototype/battle-ui/battle-motion.ts';
let count = 0;
function check(name: string, test: () => void) { test(); count++; console.log(`PASS ${name}`); }
const initial = () => initialDemo('gatekeeper-v1');
const cast = (s: DemoState, id: SkillId) => demoReducer(demoReducer(s, { type:'select', id }), { type:'cast' });
const advance = (s: DemoState) => demoReducer(s, { type:'advance' });
const round = (s: DemoState, id: SkillId) => advance(advance(advance(cast(s,id))));
const run = (ids: SkillId[]) => ids.reduce(round,initial());
check('New boss is explicit opt-in; old 48/60/8 fixture unchanged', () => { assert.deepEqual(DEMO_RULES,{playerMaxHp:48,enemyMaxHp:60,enemyDamage:8}); assert.equal(getEnemySkill(initialDemo()).damage,8); assert.deepEqual(BOSS_SKILLS.map(s=>s.damage),[16,36]); });
check('Deterministic visible 16/36 cycle', () => { for(let turn=1;turn<=8;turn++) assert.equal(getEnemySkill({...initial(),turn}).damage,turn%2 ? 16:36); });
check('Turn does not advance while player or enemy result is being shown', () => { const s=cast(initial(),'water'); assert.equal(advance(s).turn,1); assert.equal(advance(advance(s)).turn,1); assert.equal(round(initial(),'water').turn,2); });
check('Water weakens normal 16 to 13', () => assert.equal(round(initial(),'water').playerHp,35));
check('Water weakens heavy 36 to 29', () => assert.equal(round({...initial(),turn:2},'water').incoming,29));
check('Wave mitigates heavy 36 to 25 after capped heal', () => { const s=cast({...initial(),turn:2,playerHp:30},'wave'); assert.equal(s.healing,10); const n=advance(advance(s)); assert.equal(n.incoming,25); assert.equal(n.playerHp,15); });
check('One final rounding applies after weaken and mitigation', () => { const s={...initial(),phase:'enemyReady' as const,weaken:.2,mitigation:.3,turn:2}; assert.equal(advance(s).incoming,20); });
check('Enemy still hits at low player HP; no fake safety refusal', () => { const s=round({...initial(),playerHp:2},'water'); assert.equal(s.incoming,2); assert.equal(s.phase,'lost'); });
check('Kill prevents heavy retaliation', () => { const s=advance(cast({...initial(),turn:2,enemyHp:10,playerHp:3},'water')); assert.equal(s.phase,'won'); assert.equal(s.playerHp,3); });
check('Reset retains selected boss profile and restarts cycle', () => { const s=demoReducer(round(initial(),'water'),{type:'reset'}); assert.deepEqual(s,initial()); assert.equal(getEnemySkill(s).damage,16); });
check('Every skill preview equals uncapped next hit', () => { for(const turn of [1,2]) for(const skill of DEMO_SKILLS){const s=demoReducer({...initial(),turn},{type:'select',id:skill.id}); assert.equal(previewIncoming(s),advance(advance(cast(s,skill.id))).incoming); } });
check('Pure water loses round 3, mixed fast path wins round 4 with 12 HP', () => { const lost=run(['water','water','water']); assert.equal(lost.phase,'lost'); assert.equal(lost.turn,3); const won=run(['water','water','tide','water']); assert.equal(won.phase,'won'); assert.equal(won.turn,4); assert.equal(won.playerHp,12); });
check('Sustain wins later: six tides, 32 HP', () => { const s=run(Array(6).fill('tide')); assert.equal(s.phase,'won'); assert.equal(s.turn,6); assert.equal(s.playerHp,32); });
check('Wave offers another winning path, not compulsory defense', () => { const s=run(['water','wave','tide','tide','tide','water']); assert.equal(s.phase,'won'); assert.equal(s.playerHp,18); });
check('Exhaustive up-to-8-turn HP invariants and multiple wins', () => { let states=[initial()],wins=0; for(let d=0;d<8;d++){const next: DemoState[]=[]; for(const s of states)for(const skill of DEMO_SKILLS){const n=round(s,skill.id); assert.ok(n.playerHp>=0&&n.playerHp<=48&&n.enemyHp>=0&&n.enemyHp<=60); if(n.phase==='won')wins++; else if(n.phase==='choose')next.push(n);}states=next;} assert.equal(wins,26); });
check('All player hit times remain 40%, with >=1200ms to read result', () => { for(const motion of Object.values(PLAYER_MOTION)){assert.equal(motion.impactMs/motion.durationMs,.4); assert.ok(motion.durationMs-motion.impactMs>=1200);} });
check('Boss impact 960ms, then 1440ms result', () => { assert.deepEqual(BOSS_MOTION,{durationMs:2400,impactMs:960}); assert.equal(activeMotion(advance(advance(cast(initial(),'water')))),BOSS_MOTION); });
check('All three player spells withhold both HP until impact', () => { for(const skill of DEMO_SKILLS){const s=cast({...initial(),playerHp:25},skill.id); assert.deepEqual(displayedHp(s,true),{player:25,enemy:60}); assert.deepEqual(displayedHp(s,false),{player:s.playerHp,enemy:s.enemyHp});} });
check('Enemy windup withholds loss but not previous healing', () => { const s=advance(advance(cast({...initial(),playerHp:20},'tide'))); assert.deepEqual(displayedHp(s,true),{player:42,enemy:50}); assert.deepEqual(displayedHp(s,false),{player:26,enemy:50}); });
check('Idle/end phases never hide real HP even with stale pending', () => { for(const s of [initial(),run(['water','water','water']),run(['water','water','tide','water'])]){assert.equal(activeMotion(s),null); assert.equal(displayedHp(s,true).player,s.playerHp); assert.equal(displayedHp(s,true).enemy,s.enemyHp);} });
check('Motion keys distinguish player/enemy and subsequent rounds', () => { const s=cast(initial(),'water'); assert.notEqual(motionKey(s),motionKey(advance(advance(s)))); assert.notEqual(motionKey(s),motionKey(cast(round(initial(),'water'),'water'))); });
const read=(name:string)=>readFileSync(new URL(`../app/prototype/battle-ui/${name}`,import.meta.url),'utf8');
const page=read('page.tsx'), css=read('boss-motion.css'), rig=read('boss-caster.tsx');
check('Page uses current V2 boss profile, visible details and projected damage; V1 fixture tests retained', () => { assert.match(page,/'gatekeeper-v2', initialDemo/); assert.match(page,/BOSS_SKILLS_V2.map/); assert.match(page,/previewIncoming\(state\)/); assert.match(page,/可击杀 · 不反击/); });
check('Manual next reveals pending impact before advancing; reset clears presentation', () => { assert.match(page,/if \(awaitingImpact\) setShownImpact\(currentMotionKey\);\s*else dispatch/); assert.match(page,/function resetBattle\(\) \{ setShownImpact\(null\)/); });
check('Every damage/healing float is held until impact', () => { for(const fragment of ['!awaitingImpact && state.damage > 0','!awaitingImpact && skill?.healing !== 0',"state.phase === 'enemy' && !awaitingImpact &&"]) assert.ok(page.includes(fragment)); });
check('Boss raises original arm; source patch never replaces full character', () => { assert.match(rig,/mask=\{`url\(#\$\{id\}-body\)`\}/); assert.match(rig,/gatekeeper-seam-source.png" width="1024" height="1536" clipPath=/); assert.match(css,/transform-origin:184px 643px/); assert.match(css,/rotate\(135deg\)/); });
check('Tide and wave use separate arm and effect tracks', () => { for(const name of ['bu-arm-return','bu-arm-ward','bu-tide-in','bu-ward-dome','bu-boss-punch','bu-boss-slam']) assert.ok(css.includes(`@keyframes ${name}`)); });
check('Reduced motion bypasses pending and hides effects, cleanup watches preference', () => { assert.match(page,/!reducedMotion && shownImpact !== currentMotionKey/); assert.match(page,/removeEventListener\('change', sync\)/); assert.match(css,/prefers-reduced-motion/); assert.match(css,/\.bu-water-show, \.bu-tide-show, \.bu-wave-show, \.bu-boss-show, \.bu-vfx \{ display:none/); });
check('No animation event mutates battle; all five motions are pointer-transparent', () => { assert.doesNotMatch(page+rig,/onAnimationEnd|onTransitionEnd|requestAnimationFrame|localStorage/); assert.match(css,/\.bu-tide-show, \.bu-wave-show, \.bu-boss-show \{[^}]*pointer-events:none/); });
console.log(`${count}/${count} BOSS/motion checks PASS`);
