import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DEMO_RULES, DEMO_SKILLS, demoReducer, initialDemo, skillDescription, type DemoState, type SkillId } from '../app/prototype/battle-ui/demo-model.ts';
import { WATER_MOTION, waterIsCasting, presentedEnemyHp } from '../app/prototype/battle-ui/water-motion.ts';
let checks = 0;
function check(name: string, test: () => void) { test(); checks++; console.log(`PASS ${name}`); }
const cast = (state: DemoState, id: SkillId) => demoReducer(demoReducer(state, { type: 'select', id }), { type: 'cast' });
const advance = (state: DemoState) => demoReducer(state, { type: 'advance' });
const round = (state: DemoState, id: SkillId) => advance(advance(advance(cast(state, id))));
check('Fixture matches frozen V2 three-skill table', () => assert.deepEqual(DEMO_SKILLS.map(({ damage, healing, weaken, mitigation }) => [damage, healing, weaken, mitigation]), [[18, 0, .2, 0], [10, 22, 0, 0], [0, 10, 0, .3]]));
check('Existing Phase A HP/enemy values retained as isolated fixture', () => assert.deepEqual(DEMO_RULES, { playerMaxHp:48, enemyMaxHp:60, enemyDamage:8 }));
check('No implicit cast without choosing', () => assert.deepEqual(demoReducer(initialDemo(), { type:'cast' }), initialDemo()));
check('Selection does not damage or heal', () => { const s=demoReducer(initialDemo(), {type:'select',id:'tide'}); assert.equal(s.playerHp,48); assert.equal(s.enemyHp,60); assert.equal(s.phase,'choose'); });
check('Water player result precedes enemy result', () => { const s=cast(initialDemo(),'water'); assert.equal(s.enemyHp,42); assert.equal(s.playerHp,48); assert.equal(s.phase,'player'); assert.equal(advance(s).phase,'enemyReady'); });
check('Damage applies once after weaken and rounding', () => { const s=round(initialDemo(),'water'); assert.equal(s.playerHp,42); assert.equal(s.incoming,6); assert.equal(s.turn,2); });
check('Double confirm is ignored', () => { const s=cast(initialDemo(),'water'); assert.equal(demoReducer(s,{type:'cast'}),s); });
check('Busy selection is ignored', () => { const s=cast(initialDemo(),'water'); assert.equal(demoReducer(s,{type:'select',id:'tide'}),s); });
check('Full health healing reports actual zero', () => assert.equal(cast(initialDemo(),'tide').healing,0));
check('Healing visible before next incoming damage', () => { const s=cast({...initialDemo(),playerHp:20},'tide'); assert.equal(s.playerHp,42); assert.equal(s.healing,22); assert.equal(s.enemyHp,50); assert.equal(advance(advance(s)).playerHp,34); });
check('Healing caps at max', () => assert.equal(cast({...initialDemo(),playerHp:44},'tide').healing,4));
check('Still wave has healing plus mitigation, not invented shield', () => { const s=cast({...initialDemo(),playerHp:30},'wave'); assert.equal(s.playerHp,40); assert.equal(s.enemyHp,60); assert.equal(s.mitigation,.3); assert.equal(advance(advance(s)).playerHp,34); });
check('One-shot mitigation clears after hit', () => { const s=round(initialDemo(),'wave'); assert.equal(s.mitigation,0); assert.equal(s.weaken,0); });
check('Kill skips enemy action', () => { const s=advance(cast({...initialDemo(),enemyHp:10},'water')); assert.equal(s.phase,'won'); assert.equal(s.playerHp,48); assert.equal(s.enemyHp,0); });
check('Defeat remains readable at zero HP', () => { const s=round({...initialDemo(),playerHp:1},'water'); assert.equal(s.phase,'lost'); assert.equal(s.playerHp,0); });
check('Terminal states reject cast/select/advance', () => { const s=advance(cast({...initialDemo(),enemyHp:1},'water')); for(const event of [{type:'cast'},{type:'select',id:'tide'},{type:'advance'}] as const) assert.deepEqual(demoReducer(s,event),s); });
check('Reset works even during feedback', () => assert.deepEqual(demoReducer(cast(initialDemo(),'water'),{type:'reset'}),initialDemo()));
check('Descriptions contain actual configured components', () => { assert.match(skillDescription(DEMO_SKILLS[0]),/18.*20%/); assert.match(skillDescription(DEMO_SKILLS[1]),/10.*22/); assert.match(skillDescription(DEMO_SKILLS[2]),/10.*30%/); });
check('All bounded skill paths stay within HP range', () => { let states=[initialDemo()]; for(let depth=0;depth<7;depth++){const next: DemoState[]=[]; for(const s of states) for(const skill of DEMO_SKILLS){const n=round(s,skill.id); assert.ok(n.playerHp>=0&&n.playerHp<=48&&n.enemyHp>=0&&n.enemyHp<=60); if(n.phase==='choose')next.push(n);} states=next;} });
const page = readFileSync(new URL('../app/prototype/battle-ui/page.tsx',import.meta.url),'utf8');
const model = readFileSync(new URL('../app/prototype/battle-ui/demo-model.ts',import.meta.url),'utf8');
const css = readFileSync(new URL('../app/prototype/battle-ui/battle-ui.css',import.meta.url),'utf8');
check('Exactly one active spirit and one enemy target markup', () => { assert.equal((page.match(/data-testid="active-spirit"/g)||[]).length,1); assert.equal((page.match(/data-testid="enemy-target"/g)||[]).length,1); });
check('No persistence or learning dependencies', () => assert.doesNotMatch(page+model,/localStorage|sessionStorage|zero-base|battleEligible|fsrs|fetch\(/i));
check('Separate confirm and timer cleanup are wired', () => { assert.match(page,/type: 'cast'/); assert.match(page,/clearTimeout/); assert.match(page,/暂停自动/); assert.match(page,/下一步/); });
check('HP accessibility, reduced motion, narrow-screen rules', () => { assert.match(page,/role="progressbar"/); assert.match(page,/aria-valuenow/); assert.match(css,/prefers-reduced-motion/); assert.match(css,/max-width:680px/); });
check('HP trail identity does not change with feedback phase', () => { assert.ok(page.includes('key={`${hp}-trail`}')); assert.ok(!page.includes('${phase}-${hp}')); assert.doesNotMatch(page,/max=\{DEMO_RULES\.[^}]+\} phase=/); });
check('Reduced-motion trail always has an explicit final width', () => assert.ok(page.includes("'--bu-final': `${hp / max * 100}%`, ...(hp < previous")));
check('Boss art replaces placeholder and PNG supports alpha', () => { assert.match(page,/gatekeeper\.png/); assert.doesNotMatch(page,/bu-enemy-token|立绘占位|立绘待定/); const png=readFileSync(new URL('../public/battle-ui/gatekeeper.png',import.meta.url)); assert.equal(png.toString('ascii',1,4),'PNG'); assert.equal(png[25],6); });
check('Idle animation is layered separately from cast movement', () => { assert.equal((page.match(/className="bu-sprite"/g)||[]).length,2); assert.match(css,/bu-idle-water/); assert.match(css,/bu-idle-stone/); assert.match(css,/bu-ally \.bu-sprite img \{ transform:scaleX\(-1\)/); });
check('Three skills have distinct, non-interactive effect layers', () => { assert.match(page,/className=\{`bu-vfx bu-vfx-\$\{state.selected\}`\} aria-hidden="true"/); assert.match(css,/pointer-events:none; z-index:3/); for(const effect of ['bu-projectile','bu-recovery','bu-guard']) assert.ok(page.includes(effect)); assert.match(page,/state.damage > 0 &&/); assert.match(page,/state.mitigation > 0 &&/); });
check('Animation never dispatches combat outcomes', () => assert.doesNotMatch(page,/onAnimationEnd|onTransitionEnd|requestAnimationFrame/));
check('Cast shows an offscreen arena before starting results', () => { assert.match(page,/bounds.top < 0 \|\| bounds.bottom > window.innerHeight/); assert.match(page,/scrollIntoView\(\{ behavior: 'instant'/); assert.match(page,/onClick=\{confirmCast\}/); });
const rig = readFileSync(new URL('../app/prototype/battle-ui/water-caster.tsx',import.meta.url),'utf8');
check('Water impact is inside its presentation and synchronized to 40% frame', () => { assert.equal(WATER_MOTION.impactMs / WATER_MOTION.durationMs,.4); assert.ok(WATER_MOTION.durationMs-WATER_MOTION.impactMs >= 1200); });
check('Windup hides only the presented loss, never modifies settled HP', () => { const s=cast(initialDemo(),'water'); assert.equal(presentedEnemyHp(s,true),60); assert.equal(presentedEnemyHp(s,false),42); assert.equal(s.enemyHp,42); });
check('Stale pending state cannot hide enemy HP outside water cast', () => { for(const s of [advance(cast(initialDemo(),'water')),cast(initialDemo(),'tide'),initialDemo()]) { assert.equal(presentedEnemyHp(s,true),s.enemyHp); assert.equal(waterIsCasting(s),false); } });
check('Water kill waits for visible impact but still skips retaliation', () => { const s=cast({...initialDemo(),enemyHp:10},'water'); assert.equal(presentedEnemyHp(s,true),10); assert.equal(presentedEnemyHp(s,false),0); assert.equal(advance(s).phase,'won'); assert.equal(advance(s).playerHp,48); });
check('Water delay is presentation-only with cleanup and reduced-motion bypass', () => { assert.match(page,/waterCasting \? WATER_MOTION.durationMs : PHASE_DURATION\[state.phase\]/); assert.match(page,/setTimeout\(\(\) => setImpactPending\(false\), WATER_MOTION.impactMs\)/); assert.match(page,/window.matchMedia\('\(prefers-reduced-motion: reduce\)'\)/); assert.match(page,/!awaitingImpact && state.damage > 0/); });
check('Arm is separately masked from original source and pivoted at shoulder', () => { assert.match(rig,/mask=\{`url\(#\$\{id\}-body\)`\}/); assert.match(rig,/className="bu-caster-arm"/); assert.match(rig,/const SOURCE = '\/battle-ui\/lange-cutout.png'/); assert.match(css,/transform-origin:478px 565px/); assert.match(css,/rotate\(88deg\)/); });
check('Rest pose, other skills and reduced motion retain the original full illustration', () => { assert.match(page,/<WaterCaster active=\{waterCasting\}/); assert.match(css,/bu-caster-art\[data-casting="true"\] \.bu-caster-rest \{ visibility:visible/); assert.match(css,/bu-caster-art\[data-casting="true"\] \.bu-caster-rig \{ visibility:hidden/); });
check('Generated shoulder background is restricted to an interior patch', () => { assert.match(rig,/lange-shoulder-source.png" width="1254" height="1254" clipPath=/); assert.match(rig,/-shoulder/); });
check('Water surge has true PNG alpha and no input handling', () => { const png=readFileSync(new URL('../public/battle-ui/water-surge.png',import.meta.url)); assert.equal(png[25],6); assert.match(css,/bu-water-show \{[^}]*pointer-events:none/); assert.match(rig,/className="bu-water-show" aria-hidden="true"/); });
console.log(`${checks}/${checks} battle UI checks PASS`);
