import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DEMO_RULES, DEMO_SKILLS, demoReducer, initialDemo, skillDescription, type DemoState, type SkillId } from '../app/prototype/battle-ui/demo-model.ts';
let checks = 0;
function check(name: string, test: () => void) { test(); checks++; console.log(`PASS ${name}`); }
const cast = (state: DemoState, id: SkillId) => demoReducer(demoReducer(state, { type: 'select', id }), { type: 'cast' });
const advance = (state: DemoState) => demoReducer(state, { type: 'advance' });
const round = (state: DemoState, id: SkillId) => advance(advance(advance(cast(state, id))));
check('Fixture matches frozen V2 three-skill table', () => assert.deepEqual(DEMO_SKILLS.map(({ damage, healing, weaken, mitigation }) => [damage, healing, weaken, mitigation]), [[18, 0, .2, 0], [10, 22, 0, 0], [0, 10, 0, .3]]));
check('Existing Phase A HP/enemy values retained as isolated fixture', () => assert.deepEqual(DEMO_RULES, { playerMaxHp:48, enemyMaxHp:60, enemyDamage:8 }));
check('No implicit cast without choosing', () => assert.deepEqual(demoReducer(initialDemo(), { type:'cast' }), initialDemo()));
check('Selection does not damage or heal', () => { const s=demoReducer(initialDemo(), {type:'select',id:'tide'}); assert.equal(s.playerHp,48); assert.equal(s.enemyHp,60); assert.equal(s.phase,'choose'); });
check('Water player result precedes enemy result', () => { const s=cast(initialDemo(),'water'); assert.equal(s.enemyHp,42); assert.equal(s.playerHp,48); assert.equal(s.phase,'player'); assert.equal(advance(s).phase,'enemyReady'); });
check('Damage applies once after weaken and rounding', () => { const s=round(initialDemo(),'water'); assert.equal(s.playerHp,42); assert.equal(s.incoming,6); assert.equal(s.turn,2); });
check('Double confirm is ignored', () => { const s=cast(initialDemo(),'water'); assert.equal(demoReducer(s,{type:'cast'}),s); });
check('Busy selection is ignored', () => { const s=cast(initialDemo(),'water'); assert.equal(demoReducer(s,{type:'select',id:'tide'}),s); });
check('Full health healing reports actual zero', () => assert.equal(cast(initialDemo(),'tide').healing,0));
check('Healing visible before next incoming damage', () => { const s=cast({...initialDemo(),playerHp:20},'tide'); assert.equal(s.playerHp,42); assert.equal(s.healing,22); assert.equal(s.enemyHp,50); assert.equal(advance(advance(s)).playerHp,34); });
check('Healing caps at max', () => assert.equal(cast({...initialDemo(),playerHp:44},'tide').healing,4));
check('Still wave has healing plus mitigation, not invented shield', () => { const s=cast({...initialDemo(),playerHp:30},'wave'); assert.equal(s.playerHp,40); assert.equal(s.enemyHp,60); assert.equal(s.mitigation,.3); assert.equal(advance(advance(s)).playerHp,34); });
check('One-shot mitigation clears after hit', () => { const s=round(initialDemo(),'wave'); assert.equal(s.mitigation,0); assert.equal(s.weaken,0); });
check('Kill skips enemy action', () => { const s=advance(cast({...initialDemo(),enemyHp:10},'water')); assert.equal(s.phase,'won'); assert.equal(s.playerHp,48); assert.equal(s.enemyHp,0); });
check('Defeat remains readable at zero HP', () => { const s=round({...initialDemo(),playerHp:1},'water'); assert.equal(s.phase,'lost'); assert.equal(s.playerHp,0); });
check('Terminal states reject cast/select/advance', () => { const s=advance(cast({...initialDemo(),enemyHp:1},'water')); for(const event of [{type:'cast'},{type:'select',id:'tide'},{type:'advance'}] as const) assert.deepEqual(demoReducer(s,event),s); });
check('Reset works even during feedback', () => assert.deepEqual(demoReducer(cast(initialDemo(),'water'),{type:'reset'}),initialDemo()));
check('Descriptions contain actual configured components', () => { assert.match(skillDescription(DEMO_SKILLS[0]),/18.*20%/); assert.match(skillDescription(DEMO_SKILLS[1]),/10.*22/); assert.match(skillDescription(DEMO_SKILLS[2]),/10.*30%/); });
check('All bounded skill paths stay within HP range', () => { let states=[initialDemo()]; for(let depth=0;depth<7;depth++){const next: DemoState[]=[]; for(const s of states) for(const skill of DEMO_SKILLS){const n=round(s,skill.id); assert.ok(n.playerHp>=0&&n.playerHp<=48&&n.enemyHp>=0&&n.enemyHp<=60); if(n.phase==='choose')next.push(n);} states=next;} });
const page = readFileSync(new URL('../app/prototype/battle-ui/page.tsx',import.meta.url),'utf8');
const model = readFileSync(new URL('../app/prototype/battle-ui/demo-model.ts',import.meta.url),'utf8');
const css = readFileSync(new URL('../app/prototype/battle-ui/battle-ui.css',import.meta.url),'utf8');
check('Exactly one active spirit and one enemy target markup', () => { assert.equal((page.match(/data-testid="active-spirit"/g)||[]).length,1); assert.equal((page.match(/data-testid="enemy-target"/g)||[]).length,1); });
check('No persistence or learning dependencies', () => assert.doesNotMatch(page+model,/localStorage|sessionStorage|zero-base|battleEligible|fsrs|fetch\(/i));
check('Separate confirm and timer cleanup are wired', () => { assert.match(page,/type: 'cast'/); assert.match(page,/clearTimeout/); assert.match(page,/暂停自动/); assert.match(page,/下一步/); });
check('HP accessibility, reduced motion, narrow-screen rules', () => { assert.match(page,/role="progressbar"/); assert.match(page,/aria-valuenow/); assert.match(css,/prefers-reduced-motion/); assert.match(css,/max-width:680px/); });
console.log(`${checks}/${checks} battle UI checks PASS`);
