import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { BOSS_SKILLS, BOSS_SKILLS_V2, DEMO_SKILLS, demoReducer, getEnemySkill, initialDemo, previewIncoming, type DemoState, type SkillId } from '../app/prototype/battle-ui/demo-model.ts';
import { BOSS_MOTION, displayedHp } from '../app/prototype/battle-ui/battle-motion.ts';
let count=0;
function check(name:string,test:()=>void) { test(); count++; console.log(`PASS ${name}`); }
const initial=()=>initialDemo('gatekeeper-v2');
const advance=(s:DemoState)=>demoReducer(s,{type:'advance'});
const cast=(s:DemoState,id:SkillId)=>demoReducer(demoReducer(s,{type:'select',id}),{type:'cast'});
const round=(s:DemoState,id:SkillId)=>advance(advance(advance(cast(s,id))));
const run=(ids:SkillId[])=>ids.reduce(round,initial());
check('New profile is 14/28, V1 remains16/36 and fixture8',()=>{assert.deepEqual(BOSS_SKILLS_V2.map(s=>s.damage),[14,28]);assert.deepEqual(BOSS_SKILLS.map(s=>s.damage),[16,36]);assert.equal(getEnemySkill(initialDemo()).damage,8);});
check('Fixed cycle does not inspect HP or chosen skill',()=>{for(let turn=1;turn<=8;turn++)for(const playerHp of [1,24,48]){const s={...initial(),turn,playerHp};assert.equal(getEnemySkill(s).damage,turn%2?14:28);}});
check('Original three skill numbers preserved',()=>assert.deepEqual(DEMO_SKILLS.map(s=>[s.damage,s.healing,s.weaken,s.mitigation]),[[18,0,.2,0],[10,22,0,0],[0,10,0,.3]]));
check('Continuous attack can narrowly win now; no forced defensive answer',()=>{const s=run(['water','water','water','water']);assert.equal(s.phase,'won');assert.equal(s.turn,4);assert.equal(s.playerHp,4);});
check('Water/water/tide/water retains meaningful recovery margin',()=>{const s=run(['water','water','tide','water']);assert.equal(s.phase,'won');assert.equal(s.turn,4);assert.equal(s.playerHp,23);});
check('Sustain is slower, six turns and48HP',()=>{const s=run(Array(6).fill('tide'));assert.equal(s.phase,'won');assert.equal(s.turn,6);assert.equal(s.playerHp,48);});
check('Wave path also wins',()=>{const s=run(['water','wave','tide','water','water']);assert.equal(s.phase,'won');assert.equal(s.turn,5);assert.equal(s.playerHp,12);});
check('Weaken and mitigation still affect heavy28',()=>{assert.equal(round({...initial(),turn:2},'water').incoming,22);assert.equal(round({...initial(),turn:2},'wave').incoming,20);});
check('Preview and next hit use same config and one rounding',()=>{for(const turn of [1,2])for(const skill of DEMO_SKILLS){const s=demoReducer({...initial(),turn},{type:'select',id:skill.id});assert.equal(previewIncoming(s),advance(advance(cast(s,skill.id))).incoming);}});
check('Low HP still loses if hit; enemy does not fake a miss',()=>{const s=round({...initial(),playerHp:2},'water');assert.equal(s.phase,'lost');assert.equal(s.incoming,2);});
check('Kill skips retaliation and reset keeps V2',()=>{const s=round({...initial(),enemyHp:10,playerHp:2},'water');assert.equal(s.phase,'won');assert.equal(s.playerHp,2);assert.deepEqual(demoReducer(s,{type:'reset'}),initial());});
check('Impact remains960ms; presentation hold cannot apply damage twice',()=>{assert.equal(BOSS_MOTION.impactMs,960);const s=advance(advance(cast(initial(),'water')));const before={...s};for(let i=0;i<8;i++)displayedHp(s,i%2===0);assert.deepEqual(s,before);assert.equal(s.playerHp,37);});
check('All skill paths up to8 rounds remain bounded; pressure allows many options',()=>{let states=[initial()],wins=0;for(let d=0;d<8;d++){const next:DemoState[]=[];for(const s of states)for(const skill of DEMO_SKILLS){const n=round(s,skill.id);assert.ok(n.playerHp>=0&&n.playerHp<=48&&n.enemyHp>=0&&n.enemyHp<=60);if(n.phase==='won')wins++;else if(n.phase==='choose')next.push(n);}states=next;}assert.ok(wins>26);console.log(`V2 winning paths through8 rounds: ${wins}`);});
const read=(f:string)=>readFileSync(new URL(`../app/prototype/battle-ui/${f}`,import.meta.url),'utf8');
const css=read('boss-motion.css'),page=read('page.tsx'),rig=read('boss-caster.tsx');
check('Live page opts into V2; labels come from V2 config',()=>{assert.match(page,/'gatekeeper-v2', initialDemo/);assert.match(page,/BOSS_SKILLS_V2.map/);assert.match(page,/guardian-impact.png/);});
check('Punch moves toward target; heavy uses a different lower-body trajectory',()=>{assert.match(css,/--bu-lunge:-132%/);assert.match(css,/--bu-lunge:-82%/);for(const track of ['bu-boss-advance','bu-boss-stomp','bu-boss-weight'])assert.ok(css.includes(`@keyframes ${track}`));assert.match(css,/40%,45% \{ transform:translate\(var\(--bu-lunge\),-2px\)/);});
check('Heavy anticipation then slam, with ground wave reaching target at40%',()=>{assert.match(css,/26%,32% \{ transform:rotate\(135deg\)/);assert.match(css,/36%,44% \{ transform:rotate\(8deg\)/);assert.match(css,/40% \{ opacity:1; transform:scaleX\(1\)/);});
check('Impact holds120ms and reveals raster burst only at hit',()=>{assert.equal(BOSS_MOTION.durationMs*(45-40)/100,120);assert.match(css,/40%,45% \{ opacity:1; transform:scale\(.9,.94\)/);assert.match(css,/0%,39.5% \{ opacity:0/);});
check('Raster impact composites at the group boundary and has no input handlers',()=>{assert.match(rig,/className="bu-boss-burst" src="\/battle-ui\/guardian-impact.png" alt=""/);assert.match(css,/\.bu-boss-show \{ mix-blend-mode:screen; \}/);assert.doesNotMatch(rig,/onClick|onAnimationEnd|onTransitionEnd/);});
check('Only scene contents shake, not HP or controls',()=>{assert.match(css,/\[data-boss-skill="quake"\] \.bu-scene \{ animation:bu-ground-shudder/);assert.doesNotMatch(css,/(?:\.bu-hp|\.bu-shell|\.bu-commands)\s*\{[^}]*bu-ground-shudder/);});
check('Reduced-motion protection still suppresses all new motion',()=>{const base=read('battle-ui.css');assert.match(base,/\.bu-shell \*.*animation:none !important; transition:none !important/);assert.match(css,/\.bu-water-show, \.bu-tide-show, \.bu-wave-show, \.bu-boss-show, \.bu-vfx \{ display:none/);});
check('Tide/wave have distinct recoil and follow-through; no full-screen flash',()=>{assert.match(css,/@keyframes bu-body-return/);assert.match(css,/40%,46% \{ transform:rotate\(112deg\)/);assert.doesNotMatch(css,/background:\s*(?:#fff|white);/);});
console.log(`${count}/${count} impact V2 checks PASS`);
